### ISSUE TITLE
CreateStore return Symbol(observable) params instead of @@observable

### ISSUE THREAD

**Issue by Aidar-Frontend-Developer** [reduxjs/redux-toolkit#2008] opened 2022-02-07 17:28 UTC
CreateStore return Symbol(observable) params instead of @@observable
I am using -   "@reduxjs/toolkit": "^1.5.0",
Because of it, Redux DevTools 3.0.3 extension doesn't work

**Comment by markerikson** [comment] 2022-02-07 17:44
What specific version of RTK and the related `redux` package do you have, as shown in your project's lockfile?

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 19:10
redux@^4.1.1:
  version "4.1.2"
  resolved "https://registry.yarnpkg.com/redux/-/redux-4.1.2.tgz#140f35426d99bb4729af760afcf79eaaac407104"
  integrity sha512-SH8PglcebESbd/shgf6mii6EIoRM0zrQyjcuQ+ojmfxjTtE0z9Y8pa62iA/OJ58qjP6j27uyW4kUF4jl/jd6sw==
  dependencies:
    "@babel/runtime" "^7.9.2"

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 19:10
"@reduxjs/toolkit@^1.5.0":
  version "1.5.1"
  resolved "https://registry.yarnpkg.com/@reduxjs/toolkit/-/toolkit-1.5.1.tgz#05daa2f6eebc70dc18cd98a90421fab7fa565dc5"
  dependencies:
    immer "^8.0.1"
    redux "^4.0.0"
    redux-thunk "^2.3.0"
    reselect "^4.0.0"

**Comment by markerikson** [comment] 2022-02-07 19:14
Hmm. The RTK version is a bit older (and you should update when you get a chance), but it does look like a current version of `redux`.

Can you put together a CodeSandbox or repo that shows this bug happening?

Also paging @Methuselah96 for further thoughts.

**Comment by phryneas** [comment] 2022-02-07 19:23
Could you please do `npm ls redux`/`yarn why redux`? The lock file is very complicated to read and often doesn't tell the full story.

**Comment by Methuselah96** [comment] 2022-02-07 19:24
This is a re-post of https://github.com/reduxjs/redux-devtools/issues/1028. I've been emailing back-and-forth with @Aidar-Frontend-Developer and I have been unable to reproduce the issue or figure out what could be causing the issue. They're unable to use Replay due to concerns of sharing the code. It seems unlikely this is an issue with RTK. My current guess is that somehow `Symbol.observable` is getting polyfilled, however two things have stumped me:

1. I have no idea how enabling or disabling the extension could make a difference since there is no polyfill in the extension starting in 3.0.3.
2. According to @Aidar-Frontend-Developer [the following "hack" works](https://github.com/reduxjs/redux-devtools/issues/1028#issuecomment-1016583099) and I have no idea why since the two imports should be equivalent.
```jsx
import { Observable, from } from 'rxjs';
import { from as strangeFrom } from 'rxjs/internal/observable/from';  

let $store;
  try {
    // @ts-ignore
    $store = from(store);
  } catch (error) {
    // @ts-ignore
    $store = strangeFrom(store);
  }
```

**Comment by Methuselah96** [comment] 2022-02-07 19:26
I have also reproduced the dependencies of their app using a `yarn.lock` shared over email and have been unable to reproduce the issue with the exact same set of dependencies. It seems like they're legitimately on `redux@4.1.0`.

**Comment by markerikson** [comment] 2022-02-07 19:27
Honestly, if _you_ haven't been able to figure out what's up, and there's no way to get a Replay due to concerns, I don't think we're going to be able to provide any further answers or ideas :(

**Comment by Methuselah96** [comment] 2022-02-07 19:28
@Aidar-Frontend-Developer Can you try the latest version of the extension just to make sure that doesn't make a difference?

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 19:31
<img width="363" alt="Снимок экрана 2022-02-07 в 22 30 34" src="https://user-images.githubusercontent.com/36470111/152858566-107ca4f5-7219-4e27-ae71-fd19a6a0f8ce.png">

**Comment by Methuselah96** [comment] 2022-02-07 19:32
@Aidar-Frontend-Developer Are you getting this warning in your console?

> Symbol.observable as defined by Redux and Redux DevTools do not match. This could cause your app to behave differently if the DevTools are not loaded. Consider polyfilling Symbol.observable before Redux is imported or avoid polyfilling Symbol.observable altogether.

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 19:33
> @Aidar-Frontend-Developer Are you getting this warning in your console?
> 
> > Symbol.observable as defined by Redux and Redux DevTools do not match. This could cause your app to behave differently if the DevTools are not loaded. Consider polyfilling Symbol.observable before Redux is imported or avoid polyfilling Symbol.observable altogether.

Yep

**Comment by Methuselah96** [comment] 2022-02-07 19:47
Or putting a breakpoint on the first line of your code before anything is imported and copy-paste that code into the console.

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 20:00
<img width="1440" alt="Снимок экрана 2022-02-07 в 23 00 28" src="https://user-images.githubusercontent.com/36470111/152862620-64edb765-8cd4-44ca-9fe8-63dbbab1a4e5.png">

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 20:05
> Got it, that explains things. Can you try putting this as the first thing that runs in your code and see what is setting `Symbol.observable` by looking at the call stack when the `debugger` statement gets hit? This code needs to get run before anything is imported.
> 
> ```
> let backingField = Symbol.observable;
> 
> Object.defineProperty(Symbol, 'observable', {
>   get: function() {
>     return backingField;
>   },
> 
>   set: function(value) {
>     debugger;
>     backingField = value;
>   }
> });
> ```

Also try to do it but debuger inside set method wasn't caused

**Comment by Methuselah96** [comment] 2022-02-07 20:25
Can you go into the Sources tab and look at the call stack when the `debugger;` statement gets hit to see what is setting `Symbol.observable`? Or are you saying that the `debugger;` statement never gets hit?

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 20:29
never gets in

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 20:33
> Can you go into the Sources tab and look at the call stack when the `debugger;` statement gets hit to see what is setting `Symbol.observable`? Or are you saying that the `debugger;` statement never gets hit?

![code](https://user-images.githubusercontent.com/36470111/152867255-9f5ce847-f051-4a1f-910f-46f5922f3143.png)

**Comment by Methuselah96** [comment] 2022-02-07 20:36
Yeah, the code needs to get run before any of the imports in your app, so the above is unlikely to catch what is setting `Symbol.observable` since it's probably being set on import.

**Comment by Methuselah96** [comment] 2022-02-07 20:41
One way to do is to turn on the "Script First Statement" breakpoint. It will hit a breakpoint in `content.bundle.js`, then `pagewrap.bundle.js`, then in `VMxxxx` (where the `xxxx` are some numbers). Once you hit that third breakpoint, copy-paste the code into the console and keep hitting continue until it hits the `debugger;` statement.

![image](https://user-images.githubusercontent.com/693755/152867854-e4c6b4c3-42a0-4138-9f7a-573a89b582e9.png)

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 20:42
You know i've just did one thing and it works now 
![code](https://user-images.githubusercontent.com/36470111/152868760-b2de319d-81b0-479c-821b-11a74928b20d.png)

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 20:54
> let backingField = Symbol.observable;
> 
> Object.defineProperty(Symbol, 'observable', {
>   get: function() {
>     return backingField;
>   },
> 
>   set: function(value) {
>     debugger;
>     backingField = value;
>   }
> });

I did and what i need to send?

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 21:01
<img width="1434" alt="Снимок экрана 2022-02-08 в 00 00 59" src="https://user-images.githubusercontent.com/36470111/152871184-36cd3b41-3da0-4237-ba59-1c931e25374d.png">

It stopped me here

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 21:05
And after all step of debug backingField return Symbol(Symbol.observable)

**Comment by Methuselah96** [comment] 2022-02-07 21:11
This is the state I'm curious about. Specifically, the call stack in the right panel.

![image](https://user-images.githubusercontent.com/693755/152872425-1c8b1db4-7947-41af-b5ac-c225f713d8a6.png)

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 22:16
Can you send me a short video how you do it, because i can't reproduce it

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 22:24
> This is the state I'm curious about. Specifically, the call stack in the right panel.
> 
> ![image](https://user-images.githubusercontent.com/693755/152872425-1c8b1db4-7947-41af-b5ac-c225f713d8a6.png)

How can i send you call stack?

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 22:31
<img width="1435" alt="Снимок экрана 2022-02-08 в 01 30 19" src="https://user-images.githubusercontent.com/36470111/152883199-d3e597f1-997f-4ce3-afd4-5bd7607a478c.png">
I don't need video i've got it :)

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 22:32
The screenshot above it's without my hack, it's with error about TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

**Comment by Methuselah96** [comment] 2022-02-07 22:38
Awesome! Based on the call stack It looks like `pspdfkit` is polyfilling `Symbol.observable` which is what is causing the issue. The three options I can think of are:

1. Figure out if there's a way to stop `pspdfkit` from polyfilling `Symbol.observable`.
2. Import `pspdfkit` as the first import in your app (assuming that they're polyfilling on import).
3. Add a dependency on `symbol-observable` and make `import Symbol_observable from 'symbol-observable';` the first line of your app.

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 22:57
after import Symbol_observable from 'symbol-observable'; what i need to write?

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 22:58
console.info('Symbol_observable', Symbol_observable);
I call and application stated work, but when i remove it, it stops to work

**Comment by Methuselah96** [comment] 2022-02-07 23:00
You shouldn't need to call anything with it, you just need to import it so that `Symbol.observable` gets polyfilled.

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 23:07
![code](https://user-images.githubusercontent.com/36470111/152887193-b825085a-ece2-451d-bae7-ff27314b1f3b.png)
I added it in Root index file and added this import nothing happened but when i just do console.log(Symbol_observable);
it starts work )

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 23:18
import 'symbol-observable'; just like that )

**Comment by Aidar-Frontend-Developer** [comment] 2022-02-07 23:20
Thank you very much )

**Comment by Methuselah96** [comment] 2022-02-07 23:24
You're welcome. Go ahead and close the issue if this resolved it.

**Closed** 2022-02-07 23:29 UTC

**Comment by MO-Lewis** [comment] 2023-03-03 10:44
Apologies for bringing this up again a year later. The solutions discussed here don't seem to work for me. 

Solutions I've tried:
- Putting `import 'symbol-observable';` into my root `index.tsx`.
- Adding `// eslint-disable-next-line` and `import Symbol_observable from 'symbol-observable';` to `index.tsx`.
- Doing the same as above, but also adding `console.info('Symbol_observable', Symbol_observable);` just below it.

Not really sure how to proceed here; its nothing breaking, but it _**is**_ a little annoying.
My `package.json` versions:
```
- "react-redux": "^8.0.2",
- "redux": "^4.2.0",
- "redux-saga": "^1.2.1",
- "symbol-observable": "^4.0.0",
- "@reduxjs/toolkit": "^1.8.5",
```
