### ISSUE TITLE
Typescript errors using Node ESM module resolution and "declaration: true"

### ISSUE THREAD

**Issue by shermify** [reduxjs/redux-toolkit#4066] opened 2024-01-12 03:26 UTC
I noticed myself and a few other people getting an error `The inferred type of X cannot be named without a reference to '../../node_modules/@reduxjs/toolkit/dist/query/react/buildHooks'. This is likely not portable. A type annotation is necessary.`

This happens when you have `declaration: true` or you're using composite projects as can be seen in my very simple reproduction here. https://github.com/shermify/redux-toolkit-ts-repro

The error in slice.ts
![Screenshot from 2024-01-11 20-05-08](https://github.com/reduxjs/redux-toolkit/assets/12567037/39a72b11-56b6-44c0-88a0-38d9e73cc4b6)

I believe the problem is that many of the types are not explicitly exported from redux-toolkit. In this case, it's looking for UseQuery, but there are many others that give me problems. I think this is an issue because ESM modules do not allow you to reach into packages or files that are not declared explicitly in the package.json. Indeed, changing module resolution to "Node" solves it, but "NodeNext", "Node16", and "bundler" have problems.  "Node" resolution is not suggested for new projects.

Exporting the types explicitly from redux-toolkit fixes it, also adding the types to the export section of the package.json of redux-toolkit fixes it.   However, there are a bunch of types that cause this error, so I'm not sure what the best solution would be. I don't think there is a workaround because the user cannot actually import the necessary types even if they wanted to manually due to ECMAScript constraints. 

![Screenshot from 2024-01-11 20-13-29](https://github.com/reduxjs/redux-toolkit/assets/12567037/917633e3-6018-46e8-95dd-338838abd423)

The use case for "declaration: true" would be, for example, creating a library with redux-toolkit actions or having a monorepo with shared packages. Let me know if any of this sounds incorrect!

**Comment by markerikson** [comment] 2024-01-12 03:43
That sounds plausible.  @eric-crowell was doing some contributions prior to RTK 2.0 related to checking type exports for this sort of thing ( https://github.com/reduxjs/redux-toolkit/pulls?q=is%3Apr+author%3Aeric-crowell ), but it's possible more changes are needed here.

**Comment by aryaemami59** [comment] 2024-03-16 18:32
@markerikson Do you think it would be worth it to try and see if it would be plausible to bundle the type definitions into one file like we're doing with the other repos?

**Comment by markerikson** [comment] 2024-03-16 18:43
@aryaemami59 : maybe. As mentioned, I ran into issues attempting to bundle them while working on RTK 2.0.  `tsup`'s bundler didn't correctly separate them out by entry point.

**Comment by joshuaellis** [comment] 2024-03-18 12:54
Hey folks, we're wanting to upgrade Strapi to use v2 of `rtk-query` but are facing this issue, is there any known workaroun or potential route to investigate 🤔

**Comment by pebubblemaps** [comment] 2024-03-18 13:31
Hi, 
Is there any update or workaround on this ? 
Thank you for your work and help !

**Comment by shermify** [comment] 2024-03-18 14:51
> Hey folks, we're wanting to upgrade Strapi to use v2 of `rtk-query` but are facing this issue, is there any known workaround or potential route to investigate 🤔

I haven't tested it thoroughly, but I believe you can still export the object and use it without destructuring. This can obviously impact the scalability of your code architecture, so it won't work for everyone. We are opting to just wait until it's fixed or there's an official conclusion.

I also just noticed the dependencies in my example were somehow totally broken. :grimacing: Apologies to anyone who tried to test with it. It's fixed now.

**Comment by phryneas** [comment] 2024-04-01 19:11
@crutchcorn sorry for kinda hijacking this, but I'd be very interested to see if this is expressive enough to handle something like this setup: https://github.com/apollographql/apollo-client-nextjs/blob/pr/rsc-preload/packages/client-react-streaming/tsup.config.ts

What do you think?

**Comment by crutchcorn** [comment] 2024-04-01 19:15
@phryneas I don't see why it wouldn't!

Unlike TSUp, which abstracts a lot of the internals of the build tooling, we're just a slot-in configuration with some default plugins for Vite to make the basics easier to tackle while still making intense customizations easier.

You still have full control over adding any other plugins (custom or otherwise) and configuration overwrites.

**Comment by phryneas** [comment] 2024-04-01 19:25
@crutchcorn Thanks, I'll take a closer look at it then when I get around to it then! :)

**Comment by chenhebing** [comment] 2024-05-09 07:07
I would like to know if there is any new progress on this issue? Thanks

**Comment by markerikson** [comment] 2024-05-09 15:57
@chenhebing : generally if the issue is open and there's no further comments or linked PRs, there's been no progress :)

**Comment by aryaemami59** [comment] 2024-05-09 22:02
I am still working on resolving this issue in a way that doesn't involve exporting internal types, so far I've had little success with it, if I make any progress I will be sure to keep everyone updated.

**Comment by aryaemami59** [comment] 2024-06-12 08:43
I should have the solution for this ready soon. In the meantime if you guys could provide me with as many examples and code snippets as possible that would be great. This is not the easiest thing to test for.

**Comment by shermify** [comment] 2024-06-12 16:08
Sorry, I had modified my original example working on an unrelated problem. The original reproduction is here, just need to run npm install and use the workspace version of TS https://github.com/shermify/redux-toolkit-ts-repro

**Comment by aryaemami59** [comment] 2024-06-12 22:59
@CarlRibbegaardh Fun fact about the `TS4023` error, if you convert the problematic type from an `interface` to a `type` alias, the problem goes away, of course in your case, I'm willing to bet you'll get a different error, but it's just weird to me how that error works, considering interfaces and `type` aliases are supposed to be somewhat interchangable.

@shermify Thank you I have your original example already, I've managed to fix it, just need more examples and code snippets to test so we can scan for problematic types that are causing this issue.

**Comment by joshuaellis** [comment] 2024-06-13 06:45
@aryaemami59 are you able to do an pre-release? I might be able to test it in the Strapi repo with the help of @jhoward1994

**Comment by mickosav** [comment] 2024-06-13 13:38
If you folks are using `pnpm` maybe take a look at this: https://github.com/microsoft/TypeScript/issues/47663#issuecomment-1270716220

It helped me solve issue without disabling declarations.

**Comment by aryaemami59** [comment] 2024-06-13 18:27
@joshuaellis I'm not a collaborator on this repo so I can't do a "pre-release", I tested the new build in the Strapi repo, it seems to work fine, but I'm not as familiar with Strapi so if you wanna test it, [this](https://github.com/aryaemami59/redux-toolkit/tree/remove-declaration-mergings) is where I'm at as of now.

**Comment by stewartmoreland** [comment] 2024-07-07 18:59
any update on this PR?

I'm attempting to configure this in my monorepo and encountering the same issues.

```
services/client.ts:3605:1242 - error TS2742: The inferred type of 'useLazyListUsersQuery' cannot be named without a reference to '../../../node_modules/@reduxjs/toolkit/dist/query/react/buildHooks'. This is likely not portable. A type annotation is necessary.
```

**Comment by CarlRibbegaardh** [comment] 2024-07-09 10:35
@stewartmoreland, I believe @aryaemami59 is still working on a PR. I saw an update from today in another thread.

Meanwhile you can patch (pnpm patch or similar) using the technique I did above. As the patches are always tied to a specific version, an upgrade would invalidate the patch, so it will not cause future issues.

**Comment by aryaemami59** [comment] 2024-07-09 11:00
@CarlRibbegaardh @stewartmoreland

> @stewartmoreland, I believe @aryaemami59 is still working on a PR. I saw an update from today in another thread.

Yeah I'm still working on it, I should be done soon, in the meantime it would really help if you guys could run this command in your CLI and let me know if it fixes the issue you're having:

```bash
npm install https://pkg.csb.dev/reduxjs/redux-toolkit/commit/beb818cb/@reduxjs/toolkit
```

**Comment by CarlRibbegaardh** [comment] 2024-07-09 12:06
> @CarlRibbegaardh @stewartmoreland
> 
> > @stewartmoreland, I believe @aryaemami59 is still working on a PR. I saw an update from today in another thread.
> 
> Yeah I'm still working on it, I should be done soon, in the meantime it would really help if you guys could run this command in your CLI and let me know if it fixes the issue you're having:
> 
> ```shell
> npm install https://pkg.csb.dev/reduxjs/redux-toolkit/commit/beb818cb/@reduxjs/toolkit
> ```

I couldn't verify the content of that url as it's in a binary format, and I don't recognize the source, so I'm not going to run it. (I did search the commit id and found the originating source.)

Text based patches is another thing. :)

**Comment by markerikson** [comment] 2024-07-09 13:20
That is a tgz tarball with the published package from the PR, generated by the CodeSandbox CI job in that PR.

You can see the URL by opening the details link for that job.

Trust me, that's safe to install. It's the exact same binary archive that would get uploaded to npm if we published that commit live.

**Comment by knotekbr** [comment] 2024-07-11 21:46
> @stewartmoreland, I believe @aryaemami59 is still working on a PR. I saw an update from today in another thread.
> 
> Meanwhile you can patch (pnpm patch or similar) using the technique I did above. As the patches are always tied to a specific version, an upgrade would invalidate the patch, so it will not cause future issues.

@CarlRibbegaardh thanks a ton for this workaround! I encountered this issue in a yarn workspaces monorepo today, and at this point it's been driving me up the wall for hours. The patch approach (specifically steps 4 + 5) worked beautifully. As a bonus, I had never used `yarn patch` before, so that's a new tool in my toolbox.

**Comment by shermify** [comment] 2024-07-15 19:33
Works for me. Thanks @aryaemami59 for all your hard work on this!

**Comment by markerikson** [comment] 2024-07-27 17:43
Fixed in https://github.com/reduxjs/redux-toolkit/releases/tag/v2.2.7 !

**Closed by markerikson** 2024-07-27 17:43 UTC
Labels: bug, rtk-query, typescript
