### ISSUE TITLE
Type 'unknown' is not assignable to type 'string'

### ISSUE THREAD

**Issue by slim-hmidi** [reduxjs/redux-toolkit#740] opened 2020-09-25 16:31 UTC
I got a typescript error when I tried to store the error received from `signIn.rejected` reducer
authenticationSlice.ts:
```ts
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { signInApi, AuthenticatedUser } from "../../api/authentication/index";

const signIn = createAsyncThunk(
  "authentication/signIn",
  async (user: AuthenticatedUser, thunkAPI) => {
    const response = await signInApi(user);
    return response.data;
  },
);

interface InitialState {
  error: string;
  successMessage: string;
  loading: string;
  user: object | null;
}
const initialState: InitialState = {
  error: "",
  successMessage: "",
  loading: "idle",
  user: null,
};
const authenticationSlice = createSlice({
  name: "authentication",
  initialState,
  reducers: {},
  extraReducers: (builder) => {
    builder.addCase(signIn.fulfilled, (state, { payload: {data, message} }) => {
      state.user = data;
      state.successMessage = message;
      state.loading = "resolved";
    });
    builder.addCase(
      signIn.rejected,
      (state, action) => {
        if (action.payload) {
          state.error = action.payload; // Type 'unknown' is not assignable to type 'string'.
        } else {
          state.error = action.error; // Type 'unknown' is not assignable to type 'string'.
        }

        state.loading = "failed";
      },
    );
  },
});

export default authenticationSlice.reducer;
```
index.ts:
```ts
import axios from "redaxios";
import urls from "../constants";

export interface AuthenticatedUser {
  username: string;
  password: string;
}

interface RegistredUser {
  username: string;
  password: string;
  email: string;
  birthday: string;
  firstName: string;
  lastName: string;
}

const signInApi = async (user: AuthenticatedUser) => {
  const { data } = await axios.post(urls.signIn, {
    method: "POST",
    body: JSON.stringify(user),
  });

  return data;
};

const signUpApi = async (user: RegistredUser) => {
  const { data } = await axios.post(urls.signUp, {
    method: "POST",
    body: JSON.stringify(user),
  });

  return data;
};

export {
  signInApi,
  signUpApi,
};
```
**@reduxjs/toolkit: 1.4.0
react: 16.13.1
react-dom: 16.13.1
cra: 3.4.0**

**Comment by phryneas** [comment] 2020-09-25 16:42
Looks like `response.data` returned by your `signInApi` is `unknown`.

**Comment by slim-hmidi** [comment] 2020-09-25 16:46
@phryneas I added the `index.ts` file.

**Comment by phryneas** [comment] 2020-09-25 16:50
Yes. It is `unknown`. You have to tell axios what return value you are expecting. See the axios docs.

This is not a bug in RTK in any way, so I'm going to close this here. If you need any more help, StackOverflow or the Reactiflux Discord channel are good ways to get help - but the github issues are only here for bugs & feature discussions.

**Closed by phryneas** 2020-09-25 16:50 UTC

**Comment by slim-hmidi** [comment] 2020-09-25 17:06
I updated the `extraReducers` without adding returning value and I fixed it:
```ts
const authenticationSlice = createSlice({
  name: "authentication",
  initialState,
  reducers: {},
  extraReducers: {
    [`${signIn.fulfilled}`]: (state, { payload: {data, message} }) => {
      state.user = data;
      state.successMessage = message;
      state.loading = "resolved";
    },
    [`${signIn.rejected}`]: (state, action) => {
      if (action.payload) {
        state.error = action.payload;
      } else {
        state.error = action.error;
      }

      state.loading = "failed";
    },
  },
});
```

**Comment by phryneas** [comment] 2020-09-25 17:09
Please don't do that. Now everything there is `any` and you have no type safety at all. If you handle it like that, you might just go and uninstall TypeScript.

Type your API in a proper way, really.
