### ISSUE TITLE
'Provider' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by Jackie1991** [reduxjs/redux-toolkit#1875] opened 2021-12-31 08:28 UTC
'Provider' cannot be used as a JSX component.
Its instance type "Provider<anyaction>" is not a valid JSX element.
Type "Provider<anyaction>" is missing the following attributes of type "elementclass": render, context, setstate, forceupdate and other 3 items.

**Comment by phryneas** [comment] 2021-12-31 08:46
That seems like you are using it potentially very wrong. Without seeing code there is nothing we can do though.

**Comment by jeyakumar-BTR** [comment] 2021-12-31 11:06
https://github.com/reduxjs/redux-toolkit/issues/1877 
please check my error
please...!

**Comment by phryneas** [comment] 2021-12-31 11:19
@jeyakumar-BTR this is completely unrelated. If you keep on spamming we will see into banning you from this issue tracker.

**Comment by phryneas** [comment] 2021-12-31 11:21
@Jackie1991 please note that this is an issue tracker and not a help forum - and that for Redux Toolkit, while your error message above would relate to react-redux, which is a separate package with a separate issue tracker. But generally, this is probably not a bug in the library but a usage error.

I'm going to close this here as a consequence.

For usage questions, please ask at StackOverflow or in the #redux channel on Reactiflux.

Please also note that your question contains so little extra information that they would probably be deleted (on SO) or ignored (in chat).

To make sure to get an answer there, please take the time to actually write down a nicely worded question in either of those communication channels, explaining what environment you are using (are you using TypeScript at all? Is this a create-react-app app or another setup? What editor are you using? Have you installed the package? Which version?) and what you have already tried to solve the problem yourself.

**Closed by phryneas** 2021-12-31 11:21 UTC
