### ISSUE TITLE
Issue with serializable-state-invariant-middleware and firebase auth state

### ISSUE THREAD

**Issue by matchatype** [reduxjs/redux-toolkit#339] opened 2020-01-31 04:07 UTC
I'm using [@reduxjs/toolkit](https://redux-starter-kit.js.org/) which is pretty awesome. However, one of the cool middleware loaded in development, [serializable-state-invariant-middleware](https://redux-starter-kit.js.org/api/other-exports#createserializablestateinvariantmiddleware) complains about a couple of keys not being serializable:

```
A non-serializable value was detected in an action, in the path: `auth`...
A non-serializable value was detected in an action, in the path: `profile.token`...
A non-serializable value was detected in an action, in the path: `firebase.profile.token`...
```

This happens once authenticated, with auth loaded in state. I suppose there's not a lot to do here, since we actually want `auth` to be in state, however the errors in console are quite annoying. The middleware can be actually configured to pass an array of dot-separated path strings to ignore when checking for serializability, but I was able to ignore only the third path successfully.

```
const configureAppStore = (preloadedState = initialState) => {
  return configureStore({
    middleware: [
      ...getDefaultMiddleware({
        thunk: {
          extraArgument: {getFirebase, getFirestore},
        },
        serializableCheck: {
          ignoredPaths: ['auth', 'profile.token', 'firebase.profile.token'],
        },
      }),
    ],
    reducer: rootReducer,
    preloadedState,
  })
}
```

Is the configuration wrong? Is there a better way to achieve full compatibility with firebase while still keeping the benefit of the middleware?

Here's [reproduction](https://github.com/matchatype/serializable-state-invariant-middleware-issue).

**Comment by markerikson** [comment] 2020-01-31 04:30
Oh, I see what the issue is.  It's complaining about the _action_, not the state paths.  Shoulda read it more carefully :)

What specific action type is being dispatched, and what are the overall contents?

Try adding that action type to the `ignoredActions` array and see what happens.

**Comment by matchatype** [comment] 2020-01-31 04:40
Oh ya, you're so right 🤦‍♂️
If you have a look at redux dev tools you see the actions are 'LOGIN' and 'SET_PROFILE'. So this would actually fix the errors:

```
const configureAppStore = (preloadedState = initialState) => {
  return configureStore({
    middleware: [
      ...getDefaultMiddleware({
        thunk: {
          extraArgument: {getFirebase, getFirestore},
        },
        serializableCheck: {
          ignoredActions: [actionTypes.LOGIN, actionTypes.SET_PROFILE],
        },
      }),
    ],
    reducer: rootReducer,
    preloadedState,
  })
}
```
Do you think it's ok to leave it like that?

**Comment by markerikson** [comment] 2020-01-31 15:18
Yeah, that should be fine.

Out of curiosity, what is actually in those actions?  Can you paste the contents here, or at least summarize what the non-serializable values really are?

**Comment by matchatype** [comment] 2020-01-31 17:10
They come out of the react-redux-firebase bindings library, which pretty much takes care of doing the "hard work" 😅 Not that firebase auth is "difficult", but I guess this library is to firebase pretty much like redux-toolkit is to redux.

Here: https://github.com/prescottprue/react-redux-firebase/blob/ce475bd8a9158620c0fa5069fa15f0065007ede2/src/actions/auth.js

**Comment by markerikson** [comment] 2020-02-15 23:34
Closing as I think we resolved the issue.

**Closed by markerikson** 2020-02-15 23:34 UTC
