### ISSUE TITLE
Typescript error message while creating slice

### ISSUE THREAD

**Issue by KodeDino** [reduxjs/redux-toolkit#1629] opened 2021-10-20 19:06 UTC
**Description**
I am currently trying to create a new slice, as usual, to pass in some status of a video player, but I am getting a typescript error as below, this is the first time I'm getting this error, all my other slices are working fine.

```
Type '(state: VideoStatusStateType, action: PayloadAction<VideoStatusType>) => void' is not assignable to type 'CaseReducer<VideoStatusStateType, { payload: any; type: string; }> | CaseReducerWithPrepare<VideoStatusStateType, PayloadAction<any, string, any, any>>'.
  Type '(state: VideoStatusStateType, action: PayloadAction<VideoStatusType>) => void' is not assignable to type 'CaseReducer<VideoStatusStateType, { payload: any; type: string; }>'.
    Types of parameters 'state' and 'state' are incompatible.
      Type 'WritableDraft<VideoStatusStateType>' is not assignable to type 'VideoStatusStateType'.
        Types of property 'videoStatus' are incompatible.
          Type 'WritableDraft<VideoStatusType> | null | undefined' is not assignable to type 'VideoStatusType | null | undefined'.
            Type 'WritableDraft<VideoStatusType>' is not assignable to type 'VideoStatusType'.
              Types of property 'reactPlayer' are incompatible.
                Type 'WritableDraft<ReactPlayer> | undefined' is not assignable to type 'ReactPlayer | undefined'.
                  Type 'WritableDraft<ReactPlayer>' is not assignable to type 'BaseReactPlayer<ReactPlayerProps>'.
                    Types of property 'refs' are incompatible.
                      Type 'WritableDraft<{ [key: string]: ReactInstance; }>' is not assignable to type '{ [key: string]: ReactInstance; }'.
                        'string' index signatures are incompatible.
                          Type 'WritableDraft<Component<any, {}, any>> | WritableDraft<Element>' is not assignable to type 'ReactInstance'.
                            Type 'WritableDraft<Component<any, {}, any>>' is not assignable to type 'ReactInstance'.
```

My slice is implemented like below:
```js
interface VideoStatusType {
  field1: someType1;
  field2: someType2;
  ....
  fieldN: someTypeN;
}

interface VideoStatusStateType {
  videoStatus?: VideoStatusType | null
}

const initialState: VideoStatusStateType = { 
  videoStatus: null
}

const videoSlice = createSlice({
  name: "videoStatus",
  initialState,
  reducers: {
    updateVideoStatus: (state: VideoStatusStateType, action: PayloadAction<VideoStatusType>) => {
      state.videoStatus = action.payload
    }
  }
});
```

The slice format is the same as other slices in my project but only this slice is giving me this type error. The error appears under `updateVideoStatus` . When I remove the type from the `initialState` the error is gone, but I am just curious what is going on with this error in case I will face the same error later in the future. Thanks in advanced for any help.

**Comment by XiyuChen-95** [comment] 2021-10-20 23:28
Kind of solve the issue, but it is just a workaround. so in my `VideoStatusType` I have a field for `reactPlayer` of type `ReactPlayer` from library `"react-player"`. The issue is fixed by changing the `reactPlayer: ReactPlayer` into `reactPlayer: any`.
But still don't know why it is causing this problem

**Closed as completed** 2021-10-23 17:42 UTC

**Comment by AntonOfTheWoods** [comment] 2022-01-27 05:19
@markerikson, could you put a link to the documentation describing what the issue is and how to solve it, so others who have this don't also waste time?

**Comment by phryneas** [comment] 2022-01-27 07:29
@AntonOfTheWoods multiple thoughts here, but this is too individual for a generic solution in the docs:

```js
  reducers: {
    updateVideoStatus: (state: VideoStatusStateType, action: PayloadAction<VideoStatusType>) => {
```
should not specify a type for `state`, we don't show that in the docs anywhere.
```js
  reducers: {
    updateVideoStatus: (state, action: PayloadAction<VideoStatusType>) => {
```
would be correct.

The root problem here though was that some object from an external api was stored in here, that was not "simple JSON", but more complex. That confuses the types and at that point is a problem with recursive types in TypeScript in general (and a immer question, not a RTK question since that type comes from there).
Since such objects should not be stored in Redux in the first place (Redux is for data, not for third-party objects with functionality) if will probably never come up if you are using your own type definitions with normal data types.

The solution of OP here was to use `any` which is a workaround and not a solution, but also it's kind of an unsupported use case from the start.
