### ISSUE TITLE
Attempted import error: 'nanoid' is not exported from '@reduxjs/toolkit'?

### ISSUE THREAD

**Issue by cuongdevjs** [reduxjs/redux-toolkit#726] opened 2020-09-14 04:15 UTC
Throw error when import nanoid from toolkit?

**Comment by phryneas** [comment] 2020-09-14 09:45
Works perfectly fine in this CodeSandbox with the current version:

https://codesandbox.io/s/rtk-nanoid-mqf8r

**Comment by markerikson** [comment] 2020-09-14 14:09
We know it's exported correctly, because we've used it :) 

If you can show a project that reproduces the issue we might be able to take a look, but I'm going to close this.

**Closed by markerikson** 2020-09-14 14:09 UTC

**Comment by cuongdevjs** [comment] 2020-09-14 14:33
thanks for your help :) I using the old version and updated, it work be fine. :)
