### ISSUE TITLE
rtk query imports fail with pnpm package manager and snowpack

### ISSUE THREAD

**Issue by DouglasDev** [reduxjs/redux-toolkit#2163] opened 2022-03-25 15:34 UTC
I'm trying to use rtk query in a project with snowpack and react, using pnpm to install the package. When I add the following import statement:
`import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';`
 And then run the dev server, I get the error:
`[12:19:17] [snowpack] Error: Package "immer" not found. Have you installed it?
[12:19:17] [snowpack] [500] /_snowpack/pkg/@reduxjs/toolkit.v1.8.0/common/redux-toolkit.esm-c546b9d2.js`

It appears that pnpm is not able to figure out that immer, redux-thunk, and reselect are dependencies for rtk as well as rtk query.  After looking into the problem for a while, I think the issue is that rtk query and rtk query react are organized as separate repos inside of a monorepo, but the file structure is not understood by pnpm. based on these docs: https://pnpm.io/workspaces I think that the problem could be resolved by adding a [pnpm-workspace.yaml](https://pnpm.io/pnpm-workspace_yaml) file with something like this (not tested):

```
packages:
  - 'query/react/*'
  - 'query/*'
  - '*'
```
As a temporary workaround, I manually installed immer, redux-thunk, and reselect as dependencies, and after that the dev server started without errors. I think I've added enough details to reproduce the issue but please let me know if you want a minimal example repo. Thanks!

**Comment by markerikson** [comment] 2022-03-25 17:12
Yeah, if you can put together an example repo, that would help.

Can't say I like the idea of having to include an extra metadata file just for `pnpm`, but of course we do want to make sure RTK works well in all scenarios.

**Comment by DouglasDev** [comment] 2022-03-25 18:48
> Yeah, if you can put together an example repo, that would help.

Here's an example: https://github.com/DouglasDev/rtk-query-pnpm-import-bug

To test: 1. install pnpm globally if you don't have it. 2. run `pnpm i` 3. run `pnpm start` to start the dev server.

> Can't say I like the idea of having to include an extra metadata file just for `pnpm`, but of course we do want to make sure RTK works well in all scenarios.

It looks like you already have metadata files for yarn workspaces so I don't see how it's any different than that. Anyway, I appreciate your help.

**Comment by DouglasDev** [comment] 2022-03-25 18:54
Okay that's a good a point, but at the same time, 99% of the npm packages I use work on pnpm without issue so I think that points to there being a specific issue with this repo.

**Comment by markerikson** [comment] 2022-03-25 18:57
In a sense, yeah. We specifically publish RTK as separate nested entry points (with and without React support).

Actually, on that note, I want to check something. It looks like that original message is from Snowpack.  Does this error still happen if you use Snowpack for the build, but either NPM or Yarn for the install?  Or is this truly a PNPM-only thing?

**Comment by phryneas** [comment] 2022-03-25 20:05
As long as you are not cloning our repo, there is no "monorepo structure" to be had here - look into the structure of the package that is actually distributed via the tarball: [https//unpkg.com/@reduxjs/toolkit/](https//unpkg.com/@reduxjs/toolkit/)

Also, looking at the pnpm lockfile of your reproduction, it seems to perfectly fine recognize the dependencies: https://github.com/DouglasDev/rtk-query-pnpm-import-bug/blob/82d1acb1df6bde54f0a97a29f8fd3072b149ec8f/pnpm-lock.yaml#L448-L465

**Comment by phryneas** [comment] 2022-03-25 20:11
Also when starting up it clearly shows that those dependencies are present:

```
> snowpack dev

[22:10:41] [snowpack] Welcome to Snowpack! Because this is your first time running
this project, Snowpack needs to prepare your dependencies. This is a one-time step
and the results will be cached for the lifetime of your project. Please wait...
[22:10:41] [snowpack] + @reduxjs/toolkit@1.8.0
[22:10:42] [snowpack] └── immer@9.0.12
[22:10:42] [snowpack] └── redux@4.1.2
[22:10:42] [snowpack] └── reselect@4.1.5
[22:10:42] [snowpack] └── redux-thunk@2.4.1
[22:10:42] [snowpack] + @reduxjs/toolkit/query@1.8.0
[22:10:43] [snowpack] + react@17.0.2
[22:10:43] [snowpack] └── object-assign@4.1.1
[22:10:43] [snowpack] + react-dom@17.0.2
[22:10:45] [snowpack] └── scheduler@0.20.2
[22:10:45] [snowpack] └── scheduler/tracing@0.20.2
[22:10:45] [snowpack] Ready!
```

So this seems to be some kind of pnpm+snowpack or configuration bug here?

**Comment by phryneas** [comment] 2022-03-25 20:14
Ah... looking at this a second time: `@reduxjs/toolkit/query` and `@reduxjs/toolkit` are on the same level. 

Maybe we should add dependencies to anything those "sub-packages" import (including `@reduxjs/toolkit`) to https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/query/package.json and https://github.com/reduxjs/redux-toolkit/blob/master/packages/toolkit/query/react/package.json ?

**Comment by phryneas** [comment] 2022-03-25 20:18
I hope you don't mind the ping @Andarist, but given your work with those "sub-folder entry point `package.json`" (I think you created those with `preconstruct` if I'm not mixing something up?), did you encounter anything like this with snowpack before?

**Comment by markerikson** [comment] 2022-03-25 20:20
> Maybe we should add dependencies to anything those "sub-packages" import

That was actually what I was wondering (without having actually looked at this yet)

**Comment by phryneas** [comment] 2022-03-25 20:29
> > Maybe we should add dependencies to anything those "sub-packages" import
> 
> That was actually what I was wondering (without having actually looked at this yet)

I just manually edited that into `node_modules` and it does not seem to change anything.

**Comment by markerikson** [comment] 2022-03-25 21:08
If I had to guess (and again I haven't looked, I'm just going off the thread so far and my own intuition): it's quite possible PNPM only looks at the info at install time? and maybe it really does need that "workspaces" file that was mentioned up top.

**Comment by Andarist** [comment] 2022-03-25 21:09
@phryneas feel free to ping me any time :)

You can't add dependencies to "subentries" - those nested `package.json` just allow you to "route" requests to specific files (through pkg.json#main/module etc) when using the classic node.js require algorithm. They don't have any effect on what dependencies are installed etc

The problem in here is that pnpm is a "strict package manager" (the same would happen with yarn's PnP). You need to declare **all** of your dependencies explicitly and you can't rely on node_modules hoisting and similar mechanisms. You basically have 3 choices:
- publish separate packages that would integrate with specific libraries, that way each one could have isolated dependencies
- add everything to dependencies
- declare optional peer dependencies

**Comment by phryneas** [comment] 2022-03-25 22:13
@Andarist the problem here is that the application does not seem to be able to access `immer`, which *is* a `dependency` of `@reduxjs/toolkit` - as soon as `@reduxjs/toolkit/query` is imported in addition to `@reduxjs/toolkit`. 

So my instinct was "maybe it is going off of `@reduxjs/toolkit/query/package.json` here, which does not declare any dependencies (`@reduxjs/toolkit/package.json` does though). But that does not seem the case. (Granted, my snowpack experience is limited to this issue, so maybe I cleaned the cache wrongly...)

To be honest, I'm quite at a loss.

**Comment by Andarist** [comment] 2022-03-25 22:27
Oh, I might have misunderstood the issue at hand in a rush. Gonna clone that repo in a moment and take a closer look.

**Comment by phryneas** [comment] 2022-03-25 22:50
@DouglasDev  we've looked into it again and chattet a bit and at this point we suspect that this is a `snowpack` bug that only occurs when pnpm sets up the folder in the way pnpm does it.

Could you open another bug issue over at snowpack please?

**Comment by Andarist** [comment] 2022-03-26 11:15
Some additional info that might come helpful for Snowpack maintainers...

This already happens when we have a source code like this:
```js
import '@reduxjs/toolkit';
import '@reduxjs/toolkit/query';
```

Where `@reduxjs/toolkit` resolves to a file specified by `@reduxjs/toolkit/package.json#module` and where that file can be simplified to:
```js
import { enableES5 } from "immer";
enableES5();
export {};
```

And where `@reduxjs/toolkit/query` resolves to a file specified by `@reduxjs/toolkit/query/package.json#main` (note that this is not correct! it should resolve to `#module`, but that's a separate issue) and where that file can be simplified to:
```js
import * as T from "@reduxjs/toolkit" // I've also tried to use a relative path here, but with no success
import * as I from "immer"
console.log({ T, I })
```

The problem seems to be in some core logic of Snowpack. In its internals we can observe that this can't be resolved properly:
https://github.com/withastro/snowpack/blob/f2252506b2fc7acdd46778103a262337d396332c/esinstall/src/entrypoints.ts#L157

There are 3 requests for `immer` there - one is related to `immer` itself so let's ignore it. Another one looks like this and is successful:
```json
{
  dep: "immer",
  cwd: "~/rtk-query-pnpm-import-bug/node_modules/.pnpm/@reduxjs+toolkit@1.8.0_react-redux@7.2.6+react@17.0.2/node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js"
}
```
whereas the one that fails looks like this:
```json
{
  dep: "immer",
  cwd: "~/rtk-query-pnpm-import-bug/node_modules/.cache/snowpack/build/@reduxjs/toolkit@1.8.0/package.json"
}
```
We can notice here that the second one happens from within the `.cache/snowpack` directory and thus the proper manifest (aka `package.json`) can't be found.

The request itself goes through this:
https://github.com/withastro/snowpack/blob/f2252506b2fc7acdd46778103a262337d396332c/snowpack/src/sources/local.ts#L278

where:
```json
{
  "id": "@reduxjs/toolkit.v1.8.0/common/redux-toolkit.esm-eaab66fb.js"
}
```

So this comes from an already preprocessed file, one for which the `entrypoint` (later used as `cwd`) is already set here as:
```json
{
  "entrypoint": "~/rtk-query-pnpm-import-bug/node_modules/.cache/snowpack/build/@reduxjs/toolkit@1.8.0/package.json"
}
```

One could compare what happens when npm/yarn are used - but my guess would be that this "request" comes from within `node_modules` and not from the cache directory. So the problem is most likely at some earlier step that I've been investigating.

**Comment by vktrl** [comment] 2022-03-26 16:34
Hoisting the dependencies to root seems to be the safest temporary fix. Essentially the same as adding the deps, but will stick out more and won't mess with versioning.

You can add this to your .npmrc:
`public-hoist-pattern[]=*redux*`

**Comment by DouglasDev** [comment] 2022-03-28 14:27
Thanks for your help. I will open an issue with snowpack.

**Comment by markerikson** [comment] 2022-06-29 02:24
Closing as it sounds like the resolution was "NOT OUR FAULT!" :)

**Closed by markerikson** 2022-06-29 02:24 UTC
