### ISSUE TITLE
Typescript | Missing type for subscribe return result?

### ISSUE THREAD

**Issue by Zurdge** [reduxjs/redux-toolkit#1553] opened 2021-09-29 10:57 UTC
It might be set as ```:any``` for a reason but I noticed that when making the following function ```const unsubscribe = store.subscribe(()=>console.log(store.getState()))``` that ```unsubscribe``` has a type of ```:any``` rather than something like ```:()=>void```

**Comment by markerikson** [comment] 2021-11-26 20:41
Hmm. Can't reproduce this atm - I see the `Unsubscribe` type from the Redux core, as expected.

Going to close this - if you can actually reproduce it, please file a CodeSandbox or repo that shows it happening.

**Closed by markerikson** 2021-11-26 20:41 UTC
Labels: typescript
