### ISSUE TITLE
[createAsyncThunk][dispatch] some errors when I dispatch an "async action"

### ISSUE THREAD

**Issue by liuyingyyx** [reduxjs/redux-toolkit#1755] opened 2021-11-18 05:42 UTC
I created thunk and added it to a slice

````
const thunk = createAsyncThunk(
  'slice/thunk',
  async (data: sometype) => {
    return somedata;
  },
);

...some slice code
extraReducers: (builder) => {
    builder.addCase(thunk.fulfilled, (state, action) => {
      state.xxx = xxx;
    })
  },
````

But when tried to dispatch（This dispatch method was created by useDispatch<somedispatchtype>）
````
dispatch(thunk(data))
````
here is an error

> redux.js:275 Uncaught Error: Actions must be plain objects. Instead, the actual type was: 'function'. You may need to add middleware to your store setup to handle dispatching other values, such as 'redux-thunk' to handle dispatching functions. See https://redux.js.org/tutorials/fundamentals/part-4-store#middleware and https://redux.js.org/tutorials/fundamentals/part-6-async-logic#using-the-redux-thunk-middleware for examples.

**Comment by phryneas** [comment] 2021-11-18 07:47
Can you show your `configureStore` call? You probably accidentally removed the thunk middleware.

**Comment by liuyingyyx** [comment] 2021-11-19 11:56
This is my `configureStore` call.
````
configureStore({
  reducer: {
    mySlice,
  },
})
````
Thanks !

**Comment by markerikson** [comment] 2021-11-19 15:51
Then something is very wrong with your project somehow, because that should have added the thunk middleware by default.

I think we need to see a CodeSandbox or a Github repo that actually shows this error happening in order to investigate any further, because this _should_ be working fine.

**Comment by markerikson** [comment] 2021-11-26 22:21
Closing due to lack of additional info. If you can provide a reproduction we can take a look.

**Closed by markerikson** 2021-11-26 22:21 UTC
