### ISSUE TITLE
TypeError: (intermediate value)(...) is not a function when using with Preact X

### ISSUE THREAD

**Issue by byshine** [reduxjs/redux-toolkit#2116] opened 2022-03-11 06:18 UTC
```
import { configureStore } from "@reduxjs/toolkit";

export const store = configureStore({
  reducer: {},
});
```

Adding `reducer: {}` triggers `Uncaught (in promise) TypeError: (intermediate value)(...) is not a function`

Anyone have any idea why?

**Comment by markerikson** [comment] 2022-06-29 02:25
Closing due to lack of reproduction.

**Closed by markerikson** 2022-06-29 02:25 UTC
