### ISSUE TITLE
Tutorials Quick Start : different file name

### ISSUE THREAD

**Issue by JEONGHWANMIN** [reduxjs/redux-toolkit#2486] opened 2022-07-05 07:17 UTC
# Tutorials Quick Start : Different File Name
https://redux-toolkit.js.org/tutorials/quick-start
![image](https://user-images.githubusercontent.com/65848374/177271396-074bae7d-1c18-4a6e-95b5-e9c2234a4d07.png)

ScreenShot is TypeScript file but file name is couterSlice.js 

* ## please fix it

**Comment by markerikson** [comment] 2023-12-06 13:28
Dupe of a few other issues, and not something we're going to be able to fix right away.

**Closed by markerikson** 2023-12-06 13:28 UTC
