### ISSUE TITLE
RTKQ: On success/error callbacks

### ISSUE THREAD

**Issue by TranquilMarmot** [reduxjs/redux-toolkit#1383] opened 2021-08-05 01:55 UTC
(this is feature request, not a bug!)

It would be really nice to be able to pass an `onSuccess`/`onError` callback to `useQuery` calls

`onSucess` would only be called when the query completes and would contain the data (and maybe other parts of `UseQueryResult` like `requestId`, `endpointName`, `startedTimeStamp`, `fulfilledTimeStamp`). `onError` would only be called when the query fails and would contain the error.

These could be passed as part of `UseQueryOptions`.

**Comment by phryneas** [comment] 2021-08-05 06:47
This is not in there by design.

I mean, when would it trigger?

Imagine, you have component A without an `onSuccess` callback that is mounted first. It triggers a request, that leads to a cache entry.

Now component B mounts. It has a `onSuccess` callback and uses the same query. Now that will never fire, since there is already a cache entry and a request is never made.

But if B mounts before A, it fires.

This would be *highly* confusing behavior.

Therefore, lifecycle events only exist on endpoint level (see [onQueryStarted](https://redux-toolkit.js.org/rtk-query/api/createApi#onquerystarted)), but not on component level.

**Comment by TranquilMarmot** [comment] 2021-08-05 14:45
If the value is already cached, wouldn't it be possible to call `onSuccess` with the cached value when the component mounts? I do see how `onError` wouldn't work in that case, since errors probably aren't cached (?)

My use case is that I have a `useLazyQuery` that is triggered when a user takes an action. Depending on the result of the query, either an error message is rendered (using the result of the query; this is not an actual error but a successful `200` that contains information) or a redirect is done with `window.location.assign()` (also using the result of the query).

Is `onQueryStarted` the suggested way of doing side effects that are the result of an async call? For example, redirecting or setting something in localstorage or cookies. I can see the reasoning that the side-effects should only happen once and components shouldn't have to care about side effects.

**Comment by SeanRoberts** [comment] 2021-08-12 20:00
I've been wondering about this myself but with mutations.  Thankfully we can get the result of a mutation but it feels like I'm colouring outside the lines a little bit.  Here's the pattern I've been using:

```typescript
const [deleteItem, { isLoading }] = useDeleteItemMutation();

const handleDelete = async () => {
  const result = await deleteItem({ id: myItem.id });
  if ('error' in result) {
    addToast('Uh oh something bad happened!')
  } else {
    addToast('Item deleted')
    redirectTo(routes.items.index)
  }
}
```

This is working fine for me, but I don't think there's anything similar for queries (not that I've needed it.)

The reason I like to do this in the component is because I might have one mutation or query that multiple components use and they all need to do different things in the success/error scenarios.

**Comment by Grapedge** [comment] 2021-10-10 19:43
Maybe we can make useQuery return a promise that can get data asynchronously to solve this problem.

- If there is currently no cache(or pass in some options), getDataAsync will fetch the remote data
- otherwise it will directly return the cached data

```ts
const { data, getDataAsync } = useQuery()

function App() {
  const { data, getDataAsync } = useQuery()
  // trigger may also returns a promise?
  const [trigger] = useLazyQuery()
  // useListProps accepts a function (may be async) that returns data , and returns the props of the MaterialList
  const listProps = useListProps((page: number): Promise<PageList<Entity>> => {
    return getDataAsync(page).unwrap()
  })
  return <MaterialList {...listProps}>{data}</MaterialList>
}
```

**Comment by tomeronen** [comment] 2021-12-19 07:07
It would be really amazing if the triger function in query hooks, would return a promise like in mutations, so the pattern discreabed above by @SeanRoberts could be implemented for queries.

**Comment by phryneas** [comment] 2021-12-19 08:15
@tomeronen if you update your RTK to 1.7, they do.

**Comment by tomeronen** [comment] 2021-12-19 08:35
Wow amazing! thank you so much for the fast replay!

**Comment by phryneas** [comment] 2021-12-19 08:54
So since `useLazyQuery` now supports this and I am very sure that we will not also add anything like this to `useQuery`, I'm going to close this issue.

**Closed by phryneas** 2021-12-19 08:54 UTC
Labels: rtk-query

**Comment by wkigenyi** [comment] 2022-02-03 01:37
@tomeronen How did you resolve this? It is not working for me somehow. On the trigger I am calling .then(res =>console.log(res.data) but I get undefined. The network shows me I am actually getting the data. What am I doing wrong ?

**Comment by wkigenyi** [comment] 2022-02-03 03:45
Correction: I changed to unwrap().then(res =>console.log(res.data),err =>console.log(err.data)), err.data has the data that I was expecting on res.data. I am surprised, is there an explanation for this?

**Comment by phryneas** [comment] 2022-02-03 07:30
@wkigenyi your query is most likely going into an error state. have you tried looking at the redux devtools (they also have RTK Query devtools) to figure out what is happening with your endpoint?

**Comment by phryneas** [comment] 2023-04-16 18:07
For everyone who still wants to push for this (and there are a lot of thumbs in both directions, and other emojis on some of the posts here):

TanStack Query just made the decision official that these callbacks will be removed in their next major version, and the accompanying blog post gives many more arguments than I have already given.

[You can read the blog post here](https://tkdodo.eu/blog/breaking-react-querys-api-on-purpose) - maybe it gives some additional context explaining our stance here.

**Comment by SeanRoberts** [comment] 2023-04-17 01:02
> TanStack Query just made the decision official that these callbacks will be removed in their next major version, and the accompanying blog post gives many more arguments than I have already given.

Worth noting that TanStack Query is not removing these callbacks for mutations, just queries.

**Comment by phryneas** [comment] 2023-04-17 06:22
True, but in our mutations you have a promise, which allows you to do the same thing :)

**Comment by SeanRoberts** [comment] 2023-04-17 13:52
Yup, that approach works fine here! I just know Dominik had a hell of a time on Twitter this weekend explaining that no, mutation callbacks aren't going away
