### ISSUE TITLE
`createAsyncThunk`: How can I either replace the `dispatch` call used, or attach meta data or a middleware for all actions?

### ISSUE THREAD

**Issue by jmccarrell-lmi** [reduxjs/redux-toolkit#924] opened 2021-03-12 16:03 UTC
I'd prefer to use the dispatch provided by `createAsyncThunk`, but it's too vanilla.

I have a dispatch that adds a meta tag, which is picked up by a middleware, which strips the tag, dresses up the action, and sends it over a websocket.

I'd like to have ALL dispatched actions [including pending, complete, etc.] to be dressed this way, but I'm not sure how I could do that using `createAsyncThunk`.

I currently have a hook to get my enhanced dispatch [which simply uses useDispatch and attaches meta data].
The simplest solution for me would be to provide that hook when i call `createAsyncThunk`. It would be leak react implementation into Redux, if it accepted a hook, so instead I'd probably need to abstract my hook...

Side note: I'm finally feeling the downside of hooks, how they deeply couple you with the React implementation. React was originally an agnostic stand-alone framework.

**Comment by markerikson** [comment] 2021-03-12 17:16
I'm not quite sure I follow what you're trying to do here. Can you show some sample code?

**Comment by phryneas** [comment] 2021-03-12 17:27
If you want to attach some meta to all your actions, the best place for that would be a middleware, as every action always goes through all middlewares before it reaches the store.

You can also wrap the store you pass into the `Provider` to have a different `dispatch`, so you would get that out of every `useDispatch` and `connect`, but not injected into a middleware like `thunk`. Also, it seems like a very unclean way of doing things.

What exactly are you trying to achieve here?

**Comment by markerikson** [comment] 2021-03-23 03:01
Seems like this is a dupe of #750 , best as I can tell.

**Comment by markerikson** [comment] 2021-06-07 04:07
Resolved by #1083 .

**Closed by markerikson** 2021-06-07 04:07 UTC
