### ISSUE TITLE
RTKQ: Typescript is unable to infer return type of hooks

### ISSUE THREAD

**Issue by trmjoa** [reduxjs/redux-toolkit#1363] opened 2021-07-29 10:09 UTC
Hi,

I am struggling with typing out some utility functions that takes the data structure returned by the RTKQ hooks.

Example:

```javascript
import { useMyData } from "./../myApi";


function doSomeMapping(query: ReturnType<typeof useMyData>){
  // query is any, cannot be infered
}


const MyComponent = () => {
   const query = useMyData();
   // query is correctly typed with autocomplete in vscode

  doSomeMapping(query); // Typescript looses the types when entering this function

}
```

It seems like when typescript  tries to extract the return type from the hook it ends up with
```
// Basically only leaves "refetch"
query: Record<string, any> & Pick<QueryActionCreatorResult<QueryDefinition<A, B, C, D string>>, "refetch">
```

While the inferred type where its executed is

```
UseQueryStateDefaultResult<QueryDefinition<A D, C, D, string>> & Pick<...>
```

Would it be possible to solve this or export a utility type which when given the QueryDefinition could be used for declaring function signatures?

Or are there some other way of achieving this?

Edit: I'm using typescript 4.3.5

**Comment by phryneas** [comment] 2021-07-29 10:17
The problem is that you can change the complete ReturnType of `useMyData` by supplying a different `selectFromResult`. And TypeScript isn't really budging on that.

Even exporting a type for that will probably be very difficult.

Right now, you can probably only get that type with trickery. Something like
```
let x;
if (false) {
	x = useMyData()
}
type Returned = NonNullable<typeof x>;
```
that would prevent the code from acutally being bundled, but plays with TS's flow analysis.

Shipping a tool to get that type might be a future feature, but for now there is nothing for that.

**Comment by MercerK** [comment] 2021-08-17 03:27
I'm running into this similar issue and was hoping to find some guidance, however, I was able to get the Return Type for a different scenario.

```typescript
const useMyFunction<R> = (
  useQuery: (...arg: any) => R
): R => {
   return useQuery()
}
```

However, I get really mixed results. If I try pushing that definition as a generic, such as

```typescript
const useMyFunction<
  R,
  T extends  (...arg: any) => R // You could even add the "=" as well
> = (
  useQuery: T
): R => {
   return useQuery()
}
```

I find that it returns a similar error such as `query: Record<string, any> & Pick<QueryActionCreatorResult<QueryDefinition<A, B, C, D string>>, "refetch">`.

I currently have a need to build a wrapper hook for the useQuery (which is autogenerated by RTK Codegen) to memoized parameters (prior to RTK's parameters). In the scenario that these parameters are not properly memoized, I get infinite re-renders and network requests as a result. This mostly happens with errors, as I don't think errors are caching the previous arguments.

```typescript
const context = useMemo(() => {
   someComplicatedObject: "bar"
}, [])

useQuery({
    myParameters: { // "myParameters" is needed only for this query. 
       ...context, // The child parameters of "myParameters" are memoized through other code.
       b: 2
   }
})
```

This particular hook requires me to create an object, add a property called "myParameters", and associate the body parameters to "myParameters". Since I'm creating a new object per render, this won't play well when something goes wrong. Thus, when generating "myParameters", I need to memoize it. My first approach was to create a typed wrapper hook around useQuery to do something like:

```typescript
const useWrapperHook = (
   useQuery: (...args: any) => any, // There are two args; first slot is the query args + skipToken, second slot is the options
   key: keyof args[0],
   arguments: args[0][key]
) => {
  // logic to memo

  // run query & return
}
```

However, I've tried many different variants of typings and I can't figure it out. If there are helper type definitions that can make these instances easier as a result, that would be amazing.

**Comment by phryneas** [comment] 2021-08-17 07:00
Unfortunately I can't change my answer a lot. These types are extremely dynamic, because they are - depending on the arguments, the return type can completely change.

I'll look if we can get this into something more reusable in the future, but even that will be difficult, and it won't be soon.

So I can only suggest you change your approach a bit for now:

```js
useQuery(useMyParam(input1, input2))
```

**Comment by phryneas** [comment] 2021-08-20 13:00
Closing this for now.

**Closed by phryneas** 2021-08-20 13:00 UTC
Labels: enhancement
