### ISSUE TITLE
createAsyncThunk optional parameters not working [type error]

### ISSUE THREAD

**Issue by DanielBailey-web** [reduxjs/redux-toolkit#2162] opened 2022-03-25 00:35 UTC
I am getting typescript error when trying to use optional input parameters. Also does not work when using default params (e.g. [from below] resetState = false)

```
import { createAsyncThunk } from "@reduxjs/toolkit";

const getSomeData = async () =>
  fetch("/api", {
    method: "GET",
  });

export const getSomeData = createAsyncThunk(
  `thunk-name/get-some-data`,
  async (resetState?: boolean | undefined) => {
    const response = await getSomeData();
    const data = (await response.json())
      .data as Data.Full;
    return data;
  }
);
```
```
dispatch(getSomeData()) // <-- Expected 1 arguments, but got 0.ts(2554) [createAsyncThunk.d.ts(107, 626): ]()An argument for 'arg' was not provided.
```
For some reason the optional param is getting set at required.

here is my tsconfig
```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Next.js",
  "extends": "./base.json",
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": ["src", "next-env.d.ts", "styles/global.css"],
  "exclude": ["node_modules", ".next", ".turbo"]
}
```

**Comment by markerikson** [comment] 2022-03-25 00:47
As a first observation, you don't need the ` | undefined`.  That's what the `?` already means.

Beyond that, this _should_ work.  Can you put together a CodeSandbox or a repo that shows this happening?  

What TS version are you using, and do you have the TS `strict: true` option set?

**Comment by DanielBailey-web** [comment] 2022-03-25 01:10
@markerikson Added tsconfig to original. Is there a code sandbox to fork from or do I need to set one up from scratch?

**Comment by markerikson** [comment] 2022-03-25 01:24
Setting one up from scratch would be best, or at least linking to your repo if it's public.  In other words, there may be something specific about your current project setup that's causing the issue here, and that's what I need to figure out.

**Comment by DanielBailey-web** [comment] 2022-03-25 01:27
Alright, I was just hoping there was a redux toolkit template that would speed up the setup haha

**Comment by markerikson** [comment] 2022-03-25 01:50
We do have a CRA RTK+TS template:

https://github.com/reduxjs/cra-template-redux-typescript

At a minimum you can load that into CRA (just change the `github.com` to `githubbox.com`, which redirects to CSB), and then fork it.

**Comment by DanielBailey-web** [comment] 2022-03-25 01:54
Here is a sandbox (couldn't actually get the sandbox to run...) where there is a type error

https://codesandbox.io/s/vigorous-star-7qtlui?file=/pages/index.tsx

**Comment by markerikson** [comment] 2022-03-25 02:08
Hmm.  Okay, I do see that error, and I'm not immediately sure what the issue is.  It's possible that something about our types just doesn't like the optional argument somehow.

**Comment by DanielBailey-web** [comment] 2022-03-25 02:13
Hmm that's interesting, it goes away when it is set to true.

**Comment by markerikson** [comment] 2022-03-25 02:16
Yup, that's what I was wondering.

`strict: true` is absolutely the right way to use TS.  If it isn't on, you're wasting a good portion of TS's ability to detect real errors.  We've also had a _bunch_ of cases where people reported similar "the TS types aren't working" issues, and it turns out that they had `strict: false` set.  Our types expect that it's set to `true`.

Sounds like that's the issue, then, so I'll close this.

**Closed by markerikson** 2022-03-25 02:16 UTC

**Comment by DanielBailey-web** [comment] 2022-03-25 02:19
Qucik [unrelated] question about the code in my sandbox; you can see I am doing some weird useMemo thing when creating the store so I can use SSR with props. It completely works and I haven't seen any bugs yet... 

That being said how bad of an idea is it?

**Comment by markerikson** [comment] 2022-03-25 02:22
I'd say it's pretty viable, on the grounds that I've done exactly the same thing myself, and I did it by copying from some examples in the Next repo :)

**Comment by DanielBailey-web** [comment] 2022-03-25 02:31
I couldn't figure out how to get the types correct in the way they do it in the <a href="https://github.com/vercel/next.js/blob/canary/examples/with-redux-thunk/store.js">example</a>. Because they are just using vanilla js. So typing the store wasn't working so I made my own solution that just uses useMemo.

**Comment by markerikson** [comment] 2022-03-25 02:34
Yeah, my solution to that was (roughly, don't have the code in front of me):

```ts
const rootReducer = combineReducers({/* *});
export type RootState = ReturnType<typeof rootReducer>

function initStore(initialState: Partial<RootState>) {
  return createStore(
    reducers,
    initialState,
    composeWithDevTools(applyMiddleware(thunkMiddleware))
  )
}

export type AppState = ReturnType<typeof initStore>;
export type AppDispatch = AppState["dispatch"];
```

**Comment by DanielBailey-web** [comment] 2022-03-25 03:50
More info on the type problem, it appears JUST turning "strictNullChecks": false will create it even on strict mode.

**Comment by markerikson** [comment] 2022-03-25 04:02
Yeah, that's the setting that usually ends up mattering for this sort of thing.
