### ISSUE TITLE
Can't turn off dev tools extenstion with configureStore

### ISSUE THREAD

**Issue by eliana-fairstreet** [reduxjs/redux-toolkit#3396] opened 2023-04-22 01:27 UTC
I'm currently running v1.9.3 and setting up my redux store as the documentation suggests. I am not able to get the redux dev tools extension to turn off. `configureStore` is not respecting `devTools: false`. I'm using the google chrome extension of Redux DevTools.

```typescript
const store = configureStore({
    reducer,
    preloadedState,
    devTools: false,
});
```

**Comment by markerikson** [comment] 2023-04-22 02:39
@eliana-fairstreet I can confirm it should definitely check that :)

https://github.com/reduxjs/redux-toolkit/blob/d3bb412e064ad6db4fa8a83f54ba20476556f665/packages/toolkit/src/configureStore.ts#L195-L201

What are you seeing happen instead?

**Comment by eliana-fairstreet** [comment] 2023-04-22 02:54
When turned off, the dev tool extension is not showing the actions firing or the state updates, but it still shows the @@INIT stage and reveals the structure of the default state.

**Comment by markerikson** [comment] 2023-04-22 03:05
Hmm. It shouldn't be seeing _anything_, because it shouldn't be getting added to the store.

Can you put together a repo that demonstrates this happening?  Normally I'd also ask you to record a Replay ( https://replay.io/record-bugs ) so that I can see what's happening on your machine, but in this case the fact that the extension is involved makes it a bit trickier.  You _could_ try downloading the Replay Firefox browser, install the Redux Devtools extension into that browser, and make the recording - worth a shot if you can try that.

**Comment by mohammad-taheri1** [comment] 2023-04-25 10:51
@eliana-fairstreet 
DevTools Show nothing in default, Can you share your code via a public repository to check?

**Comment by markerikson** [comment] 2023-08-16 16:10
Closing due to lack of repro.

**Closed by markerikson** 2023-08-16 16:10 UTC
