### ISSUE TITLE
[Typescript] Unable to create a slice creator with thunk

### ISSUE THREAD

**Issue by Losses** [reduxjs/redux-toolkit#305] opened 2020-01-05 07:37 UTC
I'm trying to build a function that return a slice and thunk, which will use generic type, here's a minimal code snippet:

```typescript
import { createSlice, PayloadAction } from '@reduxjs/toolkit'

export interface _State {
  status: 'NOT_LOADED' | 'LOADING' | 'LOADED' | 'ERROR';
  error?: string;
}

const createNrSlice = <Parameter extends object>() => {
  const startFetch = (
    state: _State,
    action: PayloadAction<Parameter>
  ) => {
    console.log(action)
  }

  const fetchFailed = (
    state: _State,
    action: PayloadAction<string>
  ) => {
    console.log(action)
  }

  const initialState: _State = {
    status: 'NOT_LOADED',
  };

  const slice = createSlice({
    name: 'testSlice', 
    initialState,
    reducers: {
      start: startFetch,
      failed: fetchFailed,
    }
  })

  slice.actions.start({} as Parameter) // ERROR
  slice.actions.failed('') // PASS
}

/*
ERROR MESSAGE:
~~~~~~~~~~~~~~~
This expression is not callable.
  Each member of the union type 'ActionCreatorWithPayload<any, string> | ActionCreatorWithNonInferrablePayload<string> | ActionCreatorWithoutPayload<string> | ActionCreatorWithOptionalPayload<...> | ActionCreatorWithPayload<...>' has signatures, but none of those signatures are compatible with each other.ts(2349)
*/
```

`slice.action.start` is expected to be something like `ActionCreatorWithPayload<Parameter>(payload: Parameter)` but I just got an error.

It's okay if i call `slice.actions.start` outside the `createNrSlice` function, but if I call it inside the function, there will be an error.

The problem is if I want to make a function return both a slice and a thunk, I must call actions inside the function.

We've discussed a lot about this problem in the Redux discord channel but got no result, and would like to know if it's a bug related to the TypeScript definition.

----
Note: Remove `extends object` near `<Parameter extends object>()` won't solve the problem.

**Comment by phryneas** [comment] 2020-01-05 08:22
Less of a bug in the typings, more of a shortcoming in TypeScript I believe.

As long as `Parameter` is an unresolved generic, it assumes every possible value for the resulting action creator. And as those have conflicting function signatures, none of them can be called.

When you return the slice and use it outside of the function with the generic, you will notice that everything works as expected.

There are two ways around it as I can see:

* casting - not very nice, but effective:
```ts
((slice.actions.start as unknown) as ActionCreatorWithPayload<Parameter>)({} as Parameter)
```
* forcing it into a specific edge-case. This can be done using the `prepare` function:
```ts
  const slice = createSlice({
    name: "testSlice",
    initialState,
    reducers: {
      start: {
        reducer: startFetch,
        prepare(payload: Parameter){return {payload}}
      },
      failed: fetchFailed
    }
  });
```
This way, there is only one possible signature and it will work as well.

I'm sorry that I can't give you a simpler/more satisfying answer than this.

**Comment by phryneas** [comment] 2020-01-05 08:26
PS: we could try to wrap all that into our `UnionToIntersection` type - that way, the resulting action creator in a purely generic environment would go from
```
ActionCreatorWithPayload<any, string> | ActionCreatorWithNonInferrablePayload<string> | ActionCreatorWithoutPayload<string> | ActionCreatorWithOptionalPayload<Parameter, string> | ActionCreatorWithPayload<...>'
```
to
```
ActionCreatorWithPayload<any, string> & ActionCreatorWithNonInferrablePayload<string> & ActionCreatorWithoutPayload<string> & ActionCreatorWithOptionalPayload<Parameter, string> & ActionCreatorWithPayload<...>'
```
which means that ALL possible method signatures would be callable. That would be a small win.

What do you think @markerikson ?

**Comment by phryneas** [comment] 2020-01-05 08:33
Oh, and a third solution that would just *circumvent* the problem: wrap the unknown into something known:

```ts
const startFetch = (state: _State, action: PayloadAction<{parameter: Parameter}>) => {
    console.log(action);
  };
```

**Comment by Losses** [comment] 2020-01-05 10:32
Hmmm I choose the second solution, thank you for the help! :D

**Comment by Losses** [comment] 2020-01-05 11:34
@phryneas Ohhhhh...

If I write something like:
```
  const slice = createSlice({
    name: "testSlice",
    initialState,
    reducers: {
      start: {
        reducer: (state: _State, action: PayloadAction<string>) => { /* Do something here */ },
        prepare(payload: Parameter){return {payload}}
      },
      failed: fetchFailed
    }
  });
```

there'll be an error, which requires `state:_State` be `Draft<_State>` which is not exported... any suggestions?

**Comment by Losses** [comment] 2020-01-05 13:52
@phryneas @markerikson Sorry but things are become more and more complex if we're trying to add some generic type to the state object with the following code:

```diff typescript

import { createSlice, PayloadAction } from '@reduxjs/toolkit'
 
- export interface _State {
+ export interface _State<Data> {
status: 'NOT_LOADED' \| 'LOADING' \| 'LOADED' \| 'ERROR';
+   data?: Data;
error?: string;
}
 
- const createNrSlice = <Parameter extends object>() => {
+ const createNrSlice = <Parameter, Data>() => {
const startFetch = (
-     state: _State,
+     state: _State<Data>,
action: PayloadAction<Parameter>
+   ) => {
+     console.log(action)
+   }
+
+   const fetchSuccess = (
+     state: _State<Data>,
+     action: PayloadAction<Data>
) => {
console.log(action)
}
 
const fetchFailed = (
-     state: _State,
+     state: _State<Data>,
action: PayloadAction<string>
) => {
console.log(action)
}
 
-   const initialState: _State = {
+   const initialState: _State<Data> = {
status: 'NOT_LOADED',
};
 
const slice = createSlice({
name: 'testSlice',
initialState,
reducers: {
-       start: startFetch,
-       failed: fetchFailed,
+       start: { // ERROR 1
+         reducer: startFetch,
+         prepare(payload: Parameter){return {payload}}
+       },
+       success: { // ERROR 2
+         reducer: startFetch,
+         prepare(payload: Data){return {payload}}
+       },
+       failed: fetchFailed, // ERROR 2
}
})
-
-   slice.actions.start({} as Parameter) // ERROR
-   slice.actions.failed('') // PASS
}

```

and here're the final code:

```typescript
import { createSlice, PayloadAction } from '@reduxjs/toolkit'

export interface _State<Data> {
  status: 'NOT_LOADED' | 'LOADING' | 'LOADED' | 'ERROR';
  data?: Data;
  error?: string;
}

const createNrSlice = <Parameter, Data>() => {
  const startFetch = (
    state: _State<Data>,
    action: PayloadAction<Parameter>
  ) => {
    console.log(action)
  }

  const fetchSuccess = (
    state: _State<Data>,
    action: PayloadAction<Data>
  ) => {
    console.log(action)
  }

  const fetchFailed = (
    state: _State<Data>,
    action: PayloadAction<string>
  ) => {
    console.log(action)
  }

  const initialState: _State<Data> = {
    status: 'NOT_LOADED',
  };

  const slice = createSlice({
    name: 'testSlice', 
    initialState,
    reducers: {
      start: {
        reducer: startFetch,
        prepare(payload: Parameter){return {payload}}
      },
      success: {
        reducer: startFetch,
        prepare(payload: Data){return {payload}}
      },
      failed: fetchFailed,
    }
  })
}
```

Here're ERROR 1:

```
Type '{ reducer: (state: _State<Data>, action: { payload: Parameter; type: string; }) => void; prepare(payload: Parameter): { payload: Parameter; }; }' is not assignable to type 'CaseReducer<_State<Data>, { payload: any; type: string; }> | CaseReducerWithPrepare<_State<Data>, { payload: any; type: string; }>'.
  Type '{ reducer: (state: _State<Data>, action: { payload: Parameter; type: string; }) => void; prepare(payload: Parameter): { payload: Parameter; }; }' is not assignable to type 'CaseReducerWithPrepare<_State<Data>, { payload: any; type: string; }>'.
    Types of property 'reducer' are incompatible.
      Type '(state: _State<Data>, action: { payload: Parameter; type: string; }) => void' is not assignable to type 'CaseReducer<_State<Data>, { payload: any; type: string; }>'.
        Types of parameters 'state' and 'state' are incompatible.
          Type '{ status: "NOT_LOADED" | "LOADING" | "LOADED" | "ERROR"; data?: Draft<Data> | undefined; error?: string | undefined; }' is not assignable to type '_State<Data>'.
            Types of property 'data' are incompatible.
              Type 'Draft<Data> | undefined' is not assignable to type 'Data | undefined'.
                Type 'Draft<Data>' is not assignable to type 'Data | undefined'.
                  Type 'Data | (Data extends object ? { -readonly [K in keyof Data]: Draft<Data[K]>; } : Data)' is not assignable to type 'Data | undefined'.
                    Type 'Data extends object ? { -readonly [K in keyof Data]: Draft<Data[K]>; } : Data' is not assignable to type 'Data | undefined'.
                      Type 'Data | { -readonly [K in keyof Data]: Draft<Data[K]>; }' is not assignable to type 'Data | undefined'.
                        Type '{ -readonly [K in keyof Data]: Draft<Data[K]>; }' is not assignable to type 'Data'.
                          '{ -readonly [K in keyof Data]: Draft<Data[K]>; }' is assignable to the constraint of type 'Data', but 'Data' could be instantiated with a different subtype of constraint '{}'.
                            Type 'Data extends object ? { -readonly [K in keyof Data]: Draft<Data[K]>; } : Data' is not assignable to type 'Data'.
                              'Data extends object ? { -readonly [K in keyof Data]: Draft<Data[K]>; } : Data' is assignable to the constraint of type 'Data', but 'Data' could be instantiated with a different subtype of constraint '{}'.
                                Type 'Draft<Data>' is not assignable to type 'Data'.
                                  'Draft<Data>' is assignable to the constraint of type 'Data', but 'Data' could be instantiated with a different subtype of constraint '{}'.
                                    Type 'Data | (Data extends object ? { -readonly [K in keyof Data]: Draft<Data[K]>; } : Data)' is not assignable to type 'Data'.
                                      'Data | (Data extends object ? { -readonly [K in keyof Data]: Draft<Data[K]>; } : Data)' is assignable to the constraint of type 'Data', but 'Data' could be instantiated with a different subtype of constraint '{}'.
                                        Type 'Data extends object ? { -readonly [K in keyof Data]: Draft<Data[K]>; } : Data' is not assignable to type 'Data'.
                                          'Data extends object ? { -readonly [K in keyof Data]: Draft<Data[K]>; } : Data' is assignable to the constraint of type 'Data', but 'Data' could be instantiated with a different subtype of constraint '{}'.
                                            Type 'Data | { -readonly [K in keyof Data]: Draft<Data[K]>; }' is not assignable to type 'Data'.
                                              'Data | { -readonly [K in keyof Data]: Draft<Data[K]>; }' is assignable to the constraint of type 'Data', but 'Data' could be instantiated with a different subtype of constraint '{}'.
                                                Type '{ -readonly [K in keyof Data]: Draft<Data[K]>; }' is not assignable to type 'Data'.
                                                  '{ -readonly [K in keyof Data]: Draft<Data[K]>; }' is assignable to the constraint of type 'Data', but 'Data' could be instantiated with a different subtype of constraint '{}'.
                                                    Type 'Draft<Data[K]>' is not assignable to type 'Data[K]'.
                                                      Type 'Data[K] | (Data[K] extends object ? { -readonly [K in keyof Data[K]]: Draft<Data[K][K]>; } : Data[K])' is not assignable to type 'Data[K]'.
                                                        Type 'Data[K] extends object ? { -readonly [K in keyof Data[K]]: Draft<Data[K][K]>; } : Data[K]' is not assignable to type 'Data[K]'.
                                                          Type 'Data[K] | { -readonly [K in keyof Data[K]]: Draft<Data[K][K]>; }' is not assignable to type 'Data[K]'.
                                                            Type '{ -readonly [K in keyof Data[K]]: Draft<Data[K][K]>; }' is not assignable to type 'Data[K]'.
                                                              Type 'Data[keyof Data] extends object ? { -readonly [K in keyof Data[keyof Data]]: Draft<Data[keyof Data][K]>; } : Data[keyof Data]' is not assignable to type 'Data[K]'.
                                                                Type 'Data[keyof Data] | { -readonly [K in keyof Data[keyof Data]]: Draft<Data[keyof Data][K]>; }' is not assignable to type 'Data[K]'.
                                                                  Type 'Data[keyof Data]' is not assignable to type 'Data[K]'.
                                                                    Type 'keyof Data' is not assignable to type 'K'.
                                                                      'keyof Data' is assignable to the constraint of type 'K', but 'K' could be instantiated with a different subtype of constraint 'string | number | symbol'.
                                                                        Type 'string | number | symbol' is not assignable to type 'K'.
                                                                          'string | number | symbol' is assignable to the constraint of type 'K', but 'K' could be instantiated with a different subtype of constraint 'string | number | symbol'.
                                                                            Type 'string' is not assignable to type 'K'.
                                                                              'string' is assignable to the constraint of type 'K', but 'K' could be instantiated with a different subtype of constraint 'string | number | symbol'.
                                                                                Type 'Data[string | number | symbol] extends object ? { -readonly [K in keyof Data[string | number | symbol]]: Draft<Data[string | number | symbol][K]>; } : Data[string | number | symbol]' is not assignable to type 'Data[K]'.
                                                                                  Type 'Data[string | number | symbol] | { -readonly [K in keyof Data[string | number | symbol]]: Draft<Data[string | number | symbol][K]>; }' is not assignable to type 'Data[K]'.
                                                                                    Type 'Data[string] | Data[number] | Data[symbol]' is not assignable to type 'Data[K]'.
                                                                                      Type 'Data[string]' is not assignable to type 'Data[K]'.
                                                                                        Type '(Data[string] extends object ? { -readonly [K in keyof Data[string]]: Draft<Data[string][K]>; } : Data[string]) | (Data[number] extends object ? { -readonly [K in keyof Data[number]]: Draft<...>; } : Data[number]) | (Data[symbol] extends object ? { -readonly [K in keyof Data[symbol]]: Draft<...>; } : Data[symbol])' is not assignable to type 'Data[K]'.
                                                                                          Type 'Data[string] extends object ? { -readonly [K in keyof Data[string]]: Draft<Data[string][K]>; } : Data[string]' is not assignable to type 'Data[K]'.
                                                                                            Type 'Data[string] | { -readonly [K in keyof Data[string]]: Draft<Data[string][K]>; }' is not assignable to type 'Data[K]'.
                                                                                              Type 'Data[string]' is not assignable to type 'Data[K]'.
                                                                                                Type 'string' is not assignable to type 'K'.
                                                                                                  'string' is assignable to the constraint of type 'K', but 'K' could be instantiated with a different subtype of constraint 'string | number | symbol'.
                                                                                                    Type 'Draft<Data[keyof Data]>' is not assignable to type 'Data[K]'.
                                                                                                      Type 'Data[keyof Data] | (Data[keyof Data] extends object ? { -readonly [K in keyof Data[keyof Data]]: Draft<Data[keyof Data][K]>; } : Data[keyof Data])' is not assignable to type 'Data[K]'.
                                                                                                        Type '(Function & Data[keyof Data]) | (String & Data[keyof Data]) | (Number & Data[keyof Data]) | (Boolean & Data[keyof Data]) | ... 6 more ... | (Date & Data[keyof Data])' is not assignable to type 'Data[K]'.
                                                                                                          Type 'Function & Data[keyof Data]' is not assignable to type 'Data[K]'.
                                                                                                            Type 'Draft<Data[string | number | symbol]>' is not assignable to type 'Data[K]'.
                                                                                                              Type 'Data[string | number | symbol] | (Data[string | number | symbol] extends object ? { -readonly [K in keyof Data[string | number | symbol]]: Draft<Data[string | number | symbol][K]>; } : Data[string | ... 1 more ... | symbol])' is not assignable to type 'Data[K]'.
                                                                                                                Type '(Function & Data[string | number | symbol]) | (String & Data[string | number | symbol]) | (Number & Data[string | number | symbol]) | ... 7 more ... | (Date & Data[string | ... 1 more ... | symbol])' is not assignable to type 'Data[K]'.
                                                                                                                  Type 'Function & Data[string | number | symbol]' is not assignable to type 'Data[K]'.
                                                                                                                    Type 'Draft<Data[string]> | Draft<Data[number]> | Draft<Data[symbol]>' is not assignable to type 'Data[K]'.
                                                                                                                      Type 'Draft<Data[string]>' is not assignable to type 'Data[K]'.
                                                                                                                        Type 'Data[string] | (Data[string] extends object ? { -readonly [K in keyof Data[string]]: Draft<Data[string][K]>; } : Data[string])' is not assignable to type 'Data[K]'.
                                                                                                                          Type '(Function & Data[string]) | (String & Data[string]) | (Number & Data[string]) | (Boolean & Data[string]) | (RegExp & Data[string]) | ... 5 more ... | (Date & Data[string])' is not assignable to type 'Data[K]'.
                                                                                                                            Type 'Function & Data[string]' is not assignable to type 'Data[K]'.ts(2322)
```

and here're ERROR 2:
```
Type '{ reducer: (state: _State<Data>, action: { payload: Parameter; type: string; }) => void; prepare(payload: Data): { payload: Data; }; }' is not assignable to type 'CaseReducer<_State<Data>, { payload: any; type: string; }> | CaseReducerWithPrepare<_State<Data>, { payload: any; type: string; }>'.
  Type '{ reducer: (state: _State<Data>, action: { payload: Parameter; type: string; }) => void; prepare(payload: Data): { payload: Data; }; }' is not assignable to type 'CaseReducerWithPrepare<_State<Data>, { payload: any; type: string; }>'.
    Types of property 'reducer' are incompatible.
      Type '(state: _State<Data>, action: { payload: Parameter; type: string; }) => void' is not assignable to type 'CaseReducer<_State<Data>, { payload: any; type: string; }>'.ts(2322)
```

I think I did something wrong and struggled to figure it out but got no result...

-----

PS: 

If I define something like:

```
interface NarrowObject {
  [key: string]: any;
}
```

and let `Data extends NarrowObject`, all the error will disappear, but that's not what expected.

**Comment by phryneas** [comment] 2020-01-05 16:52
Yeah, that's really unfortunate - generics and immer's `Draft` type generally do not play well together :( (see https://github.com/immerjs/immer/issues/345) for example.

Right now, your solution defining `Data` as `extends Record<string, any>` is actually the best thing I can think of.

I am pondering if we could do something better here, but I'm not really sure atm. if there's anything better than removing the `Draft` there completely. But that would be a little bit of a shame, because that `Draft` type *does* remove any `readonly` attributes within the state object here, which does a good job of modelling real behaviour. Gotta do some experimentation around that.

**Comment by Losses** [comment] 2020-01-13 13:19
@phryneas  Sorry, but another question about TypeScript...

I modified a little from the [official example](https://redux-toolkit.js.org/usage/usage-with-typescript#wrapping-createslice):

```typescript
import { 
  createSlice, 
  PayloadAction,
  SliceCaseReducers,
  ValidateSliceCaseReducers 
} from '@reduxjs/toolkit'

interface GenericState<T> {
  data?: T
  status: 'loading' | 'finished' | 'error'
}

type Obj = Record<string, any>

const createGenericSlice = <
  D extends Obj,
  T extends Obj,
  Reducers extends SliceCaseReducers<GenericState<T>>
>({
  name = '',
  initialState,
  reducers
}: {
  name: string
  initialState: GenericState<T>
  reducers: ValidateSliceCaseReducers<GenericState<T>, Reducers> // MARK 1
  // ALTERNATIVE WAY
  // reducers?: ValidateSliceCaseReducers<GenericState<T>, Reducers> //MARK 2
}) => {
  return createSlice({
    name,
    initialState,
    reducers: {
      start: {
        reducer(state: GenericState<T>, action: PayloadAction<D>) {
          state.status = 'loading'
          console.log(action)
        },
        prepare(payload: D){return {payload}},
      },
      success(state: GenericState<T>, action: PayloadAction<T>) {
        state.data = action.payload
        state.status = 'finished'
      },
      ...reducers
    }
  })
}
const wrappedSlice = createGenericSlice({
  name: 'test',
  initialState: { status: 'loading' } as GenericState<Obj>,
  reducers: {
    magic(state) {
      state.status = 'finished'
      state.data = {}
    }
  }
})

const actions = wrappedSlice.actions

type Actions = keyof typeof actions

// THE RESULT OF MARK 1:
// type Actions = "magic" | "start" | "success"
// THE RESULT OF MARK 2:
// type Actions = "start" | "success"

// Why "magic" disappeared?
```

My question is: Why turn the type of additional `reducers` to optional will change the type of actions

While using wrapped `createSlice`, users must always provide a reducer even if it's not necessary?

**Comment by phryneas** [comment] 2020-01-13 18:33
> @phryneas Sorry, but another question about TypeScript...
> 
> I modified a little from the [official example](https://redux-toolkit.js.org/usage/usage-with-typescript#wrapping-createslice), trying to make reducer an optional parameter, and the generic type break again:
> 
> (diff attached)
> 
> ```ts
> import { 
>   createSlice, 
>   PayloadAction,
>   SliceCaseReducers,
>   ValidateSliceCaseReducers 
> } from '@reduxjs/toolkit'
> 
> interface GenericState<T> {
>   data?: T
>   status: 'loading' | 'finished' | 'error'
> }
> 
> type Obj = Record<string, any>
> 
> const createGenericSlice = <
>   D extends Obj,
>   T extends Obj,
>   Reducers extends SliceCaseReducers<GenericState<T>>
> >({
>   name = '',
>   initialState,
>   reducers
> }: {
>   name: string
>   initialState: GenericState<T>
>   reducers: ValidateSliceCaseReducers<GenericState<T>, Reducers> // MARK 1
>   // ALTERNATIVE WAY
>   // reducers?: ValidateSliceCaseReducers<GenericState<T>, Reducers> //MARK 2
> }) => {
>   return createSlice({
>     name,
>     initialState,
>     reducers: {
>       start: {
>         reducer(state: GenericState<T>, action: PayloadAction<D>) {
>           state.status = 'loading'
>           console.log(action)
>         },
>         prepare(payload: D){return {payload}},
>       },
>       success(state: GenericState<T>, action: PayloadAction<T>) {
>         state.data = action.payload
>         state.status = 'finished'
>       },
>       ...reducers
>     }
>   })
> }
> const wrappedSlice = createGenericSlice({
>   name: 'test',
>   initialState: { status: 'loading' } as GenericState<Obj>,
>   reducers: {
>     magic(state) {
>       state.status = 'finished'
>       state.data = {}
>     }
>   }
> })
> 
> const actions = wrappedSlice.actions
> 
> type Actions = keyof typeof actions
> 
> // THE RESULT OF MARK 1:
> // type Actions = "magic" | "start" | "success"
> // THE RESULT OF MARK 2:
> // type Actions = "start" | "success"
> 
> // Why "magic" disappeared?
> ```
> 
> My question is: Why turn the type of additional `reducers` to optional will change the type of actions
> 
> While using wrapped `createSlice`, users must always provide a reducer even if it's not necessary?
> # Diff
> 
> ```diff
> +import { 
> +  createSlice, 
> +  PayloadAction,
> +  SliceCaseReducers,
> +  ValidateSliceCaseReducers 
> +} from '@reduxjs/toolkit'
> +
>  interface GenericState<T> {
>    data?: T
>    status: 'loading' | 'finished' | 'error'
>  }
> +
> +type Obj = Record<string, any>
> +
>  const createGenericSlice = <
> -  T,
> +  D extends Obj,
> +  T extends Obj,
>    Reducers extends SliceCaseReducers<GenericState<T>>
>  >({
>    name = '',
>  const createGenericSlice = <
>  }: {
>    name: string
>    initialState: GenericState<T>
> -  reducers: ValidateSliceCaseReducers<GenericState<T>, Reducers>
> +  reducers: ValidateSliceCaseReducers<GenericState<T>, Reducers> // MARK 1
> +  // ALTERNATIVE WAY
> +  // reducers?: ValidateSliceCaseReducers<GenericState<T>, Reducers> //MARK 2
>  }) => {
>    return createSlice({
>      name,
>      initialState,
>      reducers: {
> -      start(state) {
> -        state.status = 'loading'
> +      start: {
> +        reducer(state: GenericState<T>, action: PayloadAction<D>) {
> +          state.status = 'loading'
> +          console.log(action)
> +        },
> +        prepare(payload: D){return {payload}},
>        },
>        success(state: GenericState<T>, action: PayloadAction<T>) {
>          state.data = action.payload
>          state.status = 'finished'
>   const createGenericSlice = <
>  }
>  const wrappedSlice = createGenericSlice({
>    name: 'test',
> -  initialState: { status: 'loading' } as GenericState<string>,
> +  initialState: { status: 'loading' } as GenericState<Obj>,
>    reducers: {
>      magic(state) {
>        state.status = 'finished'
> -      state.data = 'hocus pocus'
> +      state.data = {}
>      }
>    }
>  })
> +
> +const actions = wrappedSlice.actions
> +
> +type Actions = keyof typeof actions
> +
> +// THE RESULT OF MARK 1:
> +// type Actions = "magic" | "start" | "success"
> +// THE RESULT OF MARK 2:
> +// type Actions = "start" | "success"
> +
> +// Why "magic" disappeared?
> ```
> 
> ![When I'm Debugging](https://user-images.githubusercontent.com/1384036/72259216-dce9a180-364a-11ea-8de3-784aa1650cb4.gif)

It doesn't disappear for me:
[codesandbox](https://codesandbox.io/s/romantic-dubinsky-o6lmf)

**Comment by Losses** [comment] 2020-01-14 01:27
Ohhhh... Thank you for the information... maybe I should write an article about how to wrap a slice properly...

**Comment by phryneas** [comment] 2020-01-14 07:27
That would be nice. But I'd wait a week or two. I'm still thinking about ways t make this less painful - you finding all those pain spots helps greatly with that by the way :)

**Comment by Losses** [comment] 2020-01-14 11:35
@phryneas Another question, [in the document](https://redux-toolkit.js.org/usage/usage-with-typescript/#wrapping-createslice), the type of initial state `GenericState<T>` and additional reducers `Reducers` was automatically inferred from the parameter.
But in many context, user don't need to pass a initial state(in this example, `GenericState<T>['data']` was defined as optional).
The problem comes here, if we want to make TypeScript know the type of `data`, it must be written in such way (maybe?): `createGenericSlice<SomeType>(param)`, but it doesn't make scene because there isn't a default type of `Reducers`, and it's hard to tell TypeScript the default type of `Reducers` comes from the parameter `reducers`.
So, you must pass both types (which is, really hard, and I can't find a way to do so), or pass nothing (which is also impossible if you want to make initial state optional).
I'm a little confused, do you have a better design pattern or practice rule?

**Comment by phryneas** [comment] 2020-01-14 19:28
Yeah, mixing explicit and inferred type parameters is unfortunatley not yet possible in TS.

There are two ways to go about this [(I just did a twitter thread on that topic)](https://twitter.com/phry/status/1217161665827033089), in your case I guess you could do the "Generics Currying" approach, so something like 


```ts
function withExpclicit<T>(){
  return function canBeInferred<Reducers>(reducers: Reducers){
    // ...
  }
}
```

**Comment by Losses** [comment] 2020-01-15 00:56
Ohhhhh.... It looks so dirty.... hope TypeScript could merge the PR mentioned on your twitter as soon as possible....

**Comment by markerikson** [comment] 2020-02-07 01:12
I think the issue is resolved at this point, so closing.

**Closed by markerikson** 2020-02-07 01:12 UTC
