### ISSUE TITLE
Typescript build error after 2.2.7+ with Next.js 13

### ISSUE THREAD

**Issue by dnbastos** [reduxjs/redux-toolkit#4754] opened 2024-12-05 16:42 UTC
After updating `@reduxjs/toolkit` to version **2.2.7** (the issue also occurs with the latest version **2.4.0**), I have a TypeScript build error in a Next.js 13 application.

**Error Details**:

When running the build command:

```bash
yarn build
$ next build --no-lint
```

I receive the following output:

```
⚠ Linting is disabled
  Checking validity of types  .Debug Failure. False expression.
```

**Important Notes**:

- I am **not** importing anything from `@reduxjs/toolkit/src/`. All imports are from:
  - `@reduxjs/toolkit`
  - `@reduxjs/toolkit/query`
  - `@reduxjs/toolkit/query/react`
- The error **only occurs from the second build onwards**. The first build after clearing the Next.js cache works fine.
- Running `tsc` directly for type checking completes without any errors.

**A temporary Workaround**:

Setting `"incremental": false` in the `tsconfig.json` file resolves the issue.

However, this disables TypeScript's incremental compilation, which is not ideal for build performance.

**Environment**:

- **Next.js Version**: 13.5.7
- **Redux Toolkit Version**: 2.2.7 and 2.4.0
- **TypeScript Version**: 5.7.2
- **Node.js Version**: 20.18.1

tsconfig.json:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    },
    "target": "ESNext",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "types": ["node", "jest", "@testing-library/jest-dom"]
  },
  "include": ["next-env.d.ts", "jest-setup.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", "cypress.config.ts"]
}
```

**Comment by markerikson** [comment] 2024-12-05 17:25
That doesn't seem like an error that gives us any actual information about what `tsc` is even doing or why it's failing, much less anything that we can debug or give advice about.

https://github.com/reduxjs/redux-toolkit/releases/tag/v2.2.7 _did_ make a bunch of changes related to "type portability", so it's certainly _possible_ that something related actually changed, but we'd need an actual repro project or a lot more error details in order to have any chance of understanding what might be going on here.

**Comment by markerikson** [comment] 2024-12-05 19:15
Well, that's at least an error trace :) but also doesn't say what code it's even trying to compile at that point.  So, seems like we still need a repro project to dig into this.

**Comment by gkonuralp** [comment] 2024-12-11 07:15
Having same error and it seems to be resolves when I downgrade to 2.2.6. Exact same trace but my project is a huge private app so I could not provide a repro project.

**Comment by dengribar** [comment] 2024-12-11 11:09
We started to have the same issue in our app after attempting to updating a bunch of dependencies, but mainly after updating Node.js to **22.11.0**, TypeScript to **5.6.3**, and mongodb driver to **6.10.0**

Fortunately, I was able to reproduce the issue in the minimal React app https://github.com/dengribar/rtkq-ts-issue-example

It looks like setting `strict: true` in `tsconfig` fixes the issue, but unfortunately we cannot set it to `true` in our app, because then TS emits several thousands of errors 😢 

So, hopefully you'll be able to fix types in RTK Query

**Comment by EskiMojo14** [comment] 2024-12-11 12:01
I could be wrong on this, but I'm pretty sure RTK is built to expect `strict` to be enabled, or at the very least `strictNullChecks`. We can't guarantee things will work correctly without it.

**Comment by markerikson** [comment] 2024-12-11 15:12
@dengribar We absolutely expect RTK to be used with strict TS. Any usage problems that occur with strict mode _off_ are out of scope and we won't address them. 

I realize that working with large codebases limits what you can do, but trust me, those "thousands of errors" are TS actually telling you that your code is potentially _broken_.  

Given that the repro so far seems to involve having strict mode off (and now that I look closely, so did the original reported TS config), I'm going to close this issue. If someone can come up with a repro that shows it happening with strict mode on, we can take another look.

**Closed by markerikson** 2024-12-11 15:12 UTC
