### ISSUE TITLE
SSR state is correctly loaded but subscribtions doesn't seem to work?

### ISSUE THREAD

**Issue by sebastienlabine** [reduxjs/redux-toolkit#2281] opened 2022-04-25 19:09 UTC
I want to use SSR to prefetch my data and keep track of all the subscription created by redux-toolkit, so that if an optimistic update is done on that prefetched data, we can still see the change. With my current setup, I can cleary see in the logs that my setup is ok for redux because the state of redux-toolkit is being loaded in my component page. However,  when I do my optimistic update, no updates are being done.

I can confirm that when I use hooks, my updates work normally. 

Am I missing something here? Is this the default behaviour?

**Output from next-redux-wrapper** (trimmed)
```json
{
"initialState": undefined,
"initialStateFromGSPorGSSR":
"oauth2API": {

"provided": {
  "CLIENTS":
  1002: ["getClient(1002)"]},
"queries":
"getClient(1002)":
"data": {"id": 1002, "enabled": true, "client_id": "worker", …}
"endpointName": "getClient"
"fulfilledTimeStamp": 1650912905811
"originalArgs": 1002
"requestId": "nxkvmWeDFRGlcfmspztv1"
"startedTimeStamp": 1650912905760
"status": "fulfilled"
"subscriptions": [
"getClient(1002)": {
"nxkvmWeDFRGlcfmspztv1": {}
  }]
}
```
**_app.ts**
```ts
function MyApp () {
  return (
       <Component {...pageProps} />}
  )
}
export default appWithTranslation(wrapper.withRedux(MyApp));
```

**[id].ts**
```ts
export const getServerSideProps: GetServerSideProps = wrapper.getServerSideProps((store) =>
    async ({ query, locale }) => {
        try {
            const id = Number.parseInt(query.id as string);
            const { data: response } = await store.dispatch<any>(clientsApi.endpoints.getClient.initiate(id));
            return {
                props: {
                    ...(await serverSideTranslations(
                        locale,
                    )),
                    client: response,
                },
            }
        } catch (error) {
            return {
                notFound: true,
            }
        }
    });
```
**api.ts**
```ts
createApi({
    extractRehydrationInfo(action, { reducerPath }) {
        if (action.type === HYDRATE) {
            console.log("hydrate", action.payload)
            return action.payload[reducerPath];
        }
    },
```
**Store.ts**
```ts
export const makeStore = () => configureStore({
    reducer: rootReducer,
    devTools: true,
    middleware: (getDefaultMiddleware) => getDefaultMiddleware({}).concat(oauth2API.middleware),
});
export const wrapper = createWrapper<Store<RootState>>(makeStore, { debug: true });
```

**Comment by phryneas** [comment] 2022-04-25 21:26
How are you doing the optimistic update?

**Comment by sebastienlabine** [comment] 2022-04-25 22:06
```ts
import { oauth2API, OAUTH2_API_TAGS } from "../oauth2-api";
import { Client } from "./Client";
import { CreateClientSecret } from "./CreateClientSecret";
export const clientsApi = oauth2API.injectEndpoints({
    endpoints: (builder) => ({
        getClients: builder.query<Client[], void>({
            providesTags: [OAUTH2_API_TAGS.CLIENTS],
            query: () => ({
                url: `/clients`,
                method: 'GET',
            }),
        }),
        getClient: builder.query<Client, number>({
            providesTags: (result, error, arg) => [{ type: OAUTH2_API_TAGS.CLIENTS, id: arg }],
            query: (id) => ({
                url: `/clients/${id}`,
                method: 'GET',
            }),
        }),
        createClientSecret: builder.mutation<Client, { id: number, secret: CreateClientSecret }>({
            query: ({ id, secret }) => ({
                url: `/clients/${id}/secrets`,
                method: 'POST',
                data: secret
            }),
            async onQueryStarted({ id }, { dispatch, queryFulfilled }) {
                try {
                    const { data } = await queryFulfilled;
                    dispatch(clientsApi.util.updateQueryData("getClient", id, (draft) => {
                        draft.client_secrets.push(data)
                    }))
                } catch (err) {
                }
            },
            invalidatesTags: (result, error, arg) => [{ type: OAUTH2_API_TAGS.CLIENTS, id: arg.id }],
        }),

    }),
    overrideExisting: true,
});

export const { useGetClientsQuery, useGetClientQuery, useCreateClientSecretMutation, } = clientsApi;
```

**Comment by phryneas** [comment] 2022-04-25 22:13
That *looks* alright on first look. I'd probably need a full reproduction of this, sorry.

**Comment by markerikson** [comment] 2022-06-29 02:19
Closing due to lack of reproduction.

**Closed by markerikson** 2022-06-29 02:19 UTC
