### ISSUE TITLE
Codegen - interface/type alias CreateUsingPostApiResponse already registered

### ISSUE THREAD

**Issue by dagi12** [reduxjs/redux-toolkit#2222] opened 2022-04-09 16:43 UTC
Codegen is throwing error on duplicate operationIds.
In my believe most of openApi spec files generated from controller method names has duplicates in operationIds.
Simple controller method names often follow "get", "create", "update", "delete" convention.

```
Error: interface/type alias CreateUsingPostApiResponse already registered
    at registerInterface (/Users/erykmariankowski/programowanie/web/zamowienia4-client/node_modules/@rtk-query/codegen-openapi/src/generate.ts:95:13)
    at generateEndpoint (/Users/erykmariankowski/programowanie/web/zamowienia4-client/node_modules/@rtk-query/codegen-openapi/src/generate.ts:198:7)
    at /Users/erykmariankowski/programowanie/web/zamowienia4-client/node_modules/@rtk-query/codegen-openapi/src/generate.ts:118:15
    at Array.map (<anonymous>)
    at generateApi (/Users/erykmariankowski/programowanie/web/zamowienia4-client/node_modules/@rtk-query/codegen-openapi/src/generate.ts:117:34)
    at async generateEndpoints (/Users/erykmariankowski/programowanie/web/zamowienia4-client/node_modules/@rtk-query/codegen-openapi/src/index.ts:14:22)
    at async run (/Users/erykmariankowski/programowanie/web/zamowienia4-client/node_modules/@rtk-query/codegen-openapi/src/bin/cli.ts:64:7)
```

**Comment by aendel** [comment] 2022-07-14 16:00
It's happening the same to me, I don't know how to handle it

**Comment by phryneas** [comment] 2022-07-14 16:18
Without a schema to reproduce it there isn't a lot we could say or do about this.

**Comment by lostdev** [comment] 2023-07-25 03:14
Getting the same issue here. Most definitely caused by duplicate operation id's as well.

 I'll see if I can get a sample schema to reproduce the issue, as my schema is huge and I unfortunately cannot share it.

**Comment by Ledragon** [comment] 2023-08-11 12:22
Any workaround on this? Stumbled on this issue as well (two delete endpoints with different arguments)

**Comment by vadimyen** [comment] 2023-12-23 20:31
The same here

**Comment by iliapnmrv** [comment] 2024-02-25 10:14
hey! any updates on this?

**Comment by itbali** [comment] 2024-02-27 20:30
this is my api.json:
```
{
  "openapi": "3.0.3",
  "info": {
    "title": "cv-builder API",
    "description": "cv-builder API",
    "version": "0.1.7"
  },
  "tags": [
    {
      "name": "company",
      "description": "Company Information API"
    },
    {
      "name": "cv",
      "description": "API for managing candidate information with CRUD operations"
    },
    {
      "name": "pic",
      "description": "API for storing pictures (avatars from cv)"
    },
    {
      "name": "task",
      "description": "API for task management"
    },
    {
      "name": "attachment",
      "description": "API for receiving attachments"
    },
    {
      "name": "admin",
      "description": "API for administrators"
    }
  ],
  "servers": [
    {
      "url": "/api/v1"
    }
  ],
  "paths": {
    "/attachments/{attachmentId}": {
      "$ref": "./resources/attachment/attachment-by-id.json"
    },
    "/tasks": {
      "$ref": "./resources/task/tasks.json"
    },
    "/tasks/{taskId}": {
      "$ref": "./resources/task/task-by-id.json"
    },
    "/pic": {
      "$ref": "./resources/pic/pic.json"
    },
    "/pic/{picId}": {
      "$ref": "./resources/pic/pic-by-id.json"
    },
    "/cv": {
      "$ref": "./resources/cv/cv.json"
    },
    "/cv/{cvId}": {
      "$ref": "./resources/cv/cv-by-id.json"
    },
    "/companies": {
      "$ref": "./resources/company/companies.json"
    },
    "/companies/{companyId}": {
      "$ref": "./resources/company/company-by-id.json"
    },
    "/admin/tasks": {
      "$ref": "./resources/admin/tasks.json"
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ]
}
```

this is config file:

```
const config: ConfigFile = {
	schemaFile: "./cv-builder-api/api.json",
	apiFile: "./src/shared/api/api.ts",
	apiImport: "api",
	outputFile: "./src/shared/api/cvApi.ts",
	// outputFiles: {
	// 	"./src/shared/api/adminApi.ts": {
	// 		hooks: true,
	// 		// filter with regExp all endpoints that not contain /admin
	// 		filterEndpoints: [doesNotContainAdmin],
	// 	},
	// 	"./src/shared/api/cvApi.ts": {
	// 		hooks: true,
	// 		// filter with regExp all endpoints that contain admin
	// 		filterEndpoints: [containsAdmin],
	// 	},
	// },
	exportName: "cvApi",
	hooks: true,
	tag: true,
};
```

As you can see - i tried approach with moving endpoints with same ending into different files, but same error appeared.

```
npx @rtk-query/codegen-openapi openapi-config.ts                                                                                        
Error: interface/type alias GetTasksApiResponse already registered
```

**Comment by itbali** [comment] 2024-02-27 21:01
found a solution for my case: 
```
import { ConfigFile } from "@rtk-query/codegen-openapi";
import { OperationDefinition } from "@rtk-query/codegen-openapi/lib/types";

// this is function returning EndpointMatcherFunction that will be used to filter admin endpoints
const shouldContainAdmin = (withAdmin: boolean)=> (
	_operationName: string,
	operationDefinition: OperationDefinition
) => {
	return operationDefinition.path.includes("/admin/") === withAdmin;
}

const config: ConfigFile = {
	schemaFile: "./cv-builder-api/api.json",
	apiFile: "./src/shared/api/api.ts",
	apiImport: "api",
	outputFiles: {
		"./src/shared/api/adminApi.ts": {
			hooks: true,
			filterEndpoints: shouldContainAdmin(true),
		},
		"./src/shared/api/cvApi.ts": {
			hooks: true,
			filterEndpoints: shouldContainAdmin(false),
		},
	},
	exportName: "cvApi",
	hooks: true,
	tag: true,
};


export default config;
```

now i have two files created with same arguments so no conflicts any more...

**Comment by markerikson** [comment] 2024-09-22 11:15
I'm going to close this because I'm not sure that there's anything we can do in the case where there's multiple definitions with the same name.

**Closed by markerikson** 2024-09-22 11:15 UTC
