### ISSUE TITLE
createSelector: Argument of type 'DefaultRootState' is not assignable to parameter of type

### ISSUE THREAD

**Issue by akichim21** [reduxjs/redux-toolkit#1976] opened 2022-01-30 03:08 UTC
When I raise the version of @reduxjs/toolkit from 1.6.2 to 1.7.1, I get the following error.

```
npx tsc

error TS2345: Argument of type 'DefaultRootState' is not assignable to parameter of type '{ readonly [$CombinedState]?: undefined; hoge: hogeEntityState; fuga: fugaEntityState; ... 20 more ...; suge: sugeEntityState; }'.
  Type 'DefaultRootState' is missing the following properties from type '{ readonly [$CombinedState]?: undefined; hoge: hogeEntityState; fuga: fugaEntityState; ... 20 more ...; suge: sugeEntityState; }': hoge, fuga, and 19 more.
```

```
import { useSelector } from "react-redux";
import { hogeSelector } from "./hogeSlice.ts";

  // error argument state
  const hoge = useSelector((state) =>
    hogeSelector(state, fuga.id)
  );
```

hogeSlice.ts
```
import {
createSelector,
createEntityAdapter,
EntityState,
createSlice,
} from "@reduxjs/toolkit";
import { RootState } from "store";
import { HYDRATE } from "next-redux-wrapper";

const adapter = createEntityAdapter<Hoge>();

const initialState: EntityState<Hoge> = adapter.getInitialState({});

/** slice **/
export const hogeSlice = createSlice({
  name: "hoge",
  initialState,
  reducers: {},
  extraReducers: (builder) => {
    builder
      .addCase(HYDRATE, (state, action: any) => {
        return { ...state, ...action.payload.hoge };
      });
});

export const {
  selectAll: hogesSelector
} = adapter.getSelectors((state: RootState) => state.hoge);

export const hogeSelector = createSelector(
  [
    hogesSelector,
    (state, fugaId: number) => fugaId,
  ],
  (entities, fugaId) => {
    return xxxx;
  }
);
```

store.ts
```
import { useDispatch } from "react-redux";
import logger from "redux-logger";
import { createWrapper } from "next-redux-wrapper";
import {
  combineReducers,
  configureStore,
  Middleware,
  // getDefaultMiddleware,
} from "@reduxjs/toolkit";

import { reducers } from "./reducers";

const rootReducer = combineReducers({
  ...reducers,
});

const createStore = () => {
  return configureStore({
    reducer: rootReducer,
    middleware: (getDefaultMiddleware) =>
      process.env.NODE_ENV === "production"
        ? getDefaultMiddleware()
        : getDefaultMiddleware().concat(logger as Middleware),
  });
};
export const store = createStore();
export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
export const useAppDispatch = () => useDispatch<AppDispatch>();
export type AppStore = ReturnType<typeof createStore>;
export const wrapper = createWrapper<AppStore>(createStore);
```

reducers.ts
```
import { hogeSlice } from "./hogeSlice";

export type ReduxState = {
  hoge: typeof hogeSlice.reducer;
};

export const reducers: ReduxState = {
  hoge: hogeSlice.reducer
};
```

package.json
```
"@reduxjs/toolkit": "^1.7.1",
"react-redux": "^7.2.6", # or "react-redux": "v8.0.0-beta.2",
"typescript": "4.5"
...
```

**Comment by phryneas** [comment] 2022-01-30 11:41
That should be fixed by #1977. Could you please try the CI build available at https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/1977 (see "local install instructions") and verify if it fixes the problem for you?

**Comment by akichim21** [comment] 2022-01-30 13:28
I try it, but other error happend.

Type 'unknown' is not assignable to type 'string'.

```
const hotelNameSelector = createSelector(stateSelector, (state) =>
  stateSelector.name
);

const name = useSelector(nameSelector);

// error happened
const str: string = name;
```

This code is a sample.
const str: string = name;
The above is an error in my repository with { str: string } in props

**Comment by phryneas** [comment] 2022-01-30 13:31
Tbh., I have no idea what `stateSelector` is here. Could you create a CodeSandbox with a self-contained example of the problem you are facing?

**Comment by akichim21** [comment] 2022-01-30 13:42
stateSelector.name is a typed string value.
A simplified version of the code is shown below.

```
const str = "name";
const nameSelector = createSelector(stateSelector, (_state) => str);

const name = useSelector(nameSelector);

// error happened
const str: string = name;
```

This doesn't happen in "@reduxjs/toolkit": "^1.6.2".
If you don't know, I create a CodeSandbox (I've never done this before, so I may not be able to).

**Comment by phryneas** [comment] 2022-01-30 13:54
From that snippet, that does seem to be completely unrelated and not even involve Redux Toolkit. Maybe it is a reselect issue, so if you create a reproduction maybe @markerikson has an idea on it.

**Comment by akichim21** [comment] 2022-01-30 14:30
My way of doing the "local install instructions" was wrong.
It's probably all fixed now. Thanks!

package.json
```
-    "@reduxjs/toolkit": "^1.6.2",
+    "@reduxjs/toolkit": "https://pkg.csb.dev/reduxjs/redux-toolkit/commit/60af3a98/@reduxjs/toolkit",
+    "@rtk-incubator/action-listener-middleware": "https://pkg.csb.dev/reduxjs/redux-toolkit/commit/60af3a98/@rtk-incubator/action-listener-middleware",
+    "@rtk-query/codegen-openapi": "https://pkg.csb.dev/reduxjs/redux-toolkit/commit/60af3a98/@rtk-query/codegen-openapi",
+    "@rtk-query/graphql-request-base-query": "https://pkg.csb.dev/reduxjs/redux-toolkit/commit/60af3a98/@rtk-query/graphql-request-base-query",
```

**Comment by akichim21** [comment] 2022-01-30 14:58
sorry. My way of doing the "local install instructions" was wrong again.
The following error still occurs
```
error TS2345: Argument of type 'DefaultRootState' is not assignable to parameter of type '{ readonly [$CombinedState]?: undefined; hoge: hogeEntityState; fuga: fugaEntityState; ... 20 more ...; suge: sugeEntityState; }'.
  Type 'DefaultRootState' is missing the following properties from type '{ readonly [$CombinedState]?: undefined; hoge: hogeEntityState; fuga: fugaEntityState; ... 20 more ...; suge: sugeEntityState; }': hoge, fuga, and 19 more.
```

However, the following methods can be used to avoid this problem, so if you cannot handle it, it is fine.
```
import { useSelector } from "react-redux";
import { hogeSelector } from "./hogeSlice.ts";

  // error don't happened
-  const hoge = useSelector((state) =>
+  const hoge = useSelector((state: any) =>
    hogeSelector(state, fuga.id)
  );
```

**Comment by phryneas** [comment] 2022-01-30 15:10
Are you using a correctly typed useSelector hook? https://redux-toolkit.js.org/tutorials/typescript#use-typed-hooks-in-components


Also, general question: why are you using `useSelector` in combination with the selector in the first place when you could just use the `useQuery` hook?

**Comment by markerikson** [comment] 2022-01-30 16:54
Yeah, you can't just do `useSelector( (state) => whatever)` by itself, because then TS doesn't know what the actual root state type is. `DefaultRootState` is an internal type inside of React-Redux that should never actually get referenced, _because_ you are supposed to either do `(state: MyAppRootState) => whatever` or `useAppSelector( (state) => whatever)`.

**Closed by markerikson** 2022-01-30 16:54 UTC

**Comment by akichim21** [comment] 2022-01-31 01:08
thanks!
I use useAppSelector.

**Comment by phryneas** [comment] 2022-01-31 07:28
Not in your code example above and according to your error message you also have `DefaultRootState`, which only appears in an untyped `useSelector` call.

**Comment by phryneas** [comment] 2022-02-03 08:41
Released in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.7.2
