### ISSUE TITLE
Property 'then' does not exist on type AsyncThunkAction

### ISSUE THREAD

**Issue by rgbutov** [reduxjs/redux-toolkit#1850] opened 2021-12-20 20:51 UTC
Hi, 
Found bug after migrate to `react-scripts: 5.0.0` and  `@reduxjs/toolkit": "1.7.0"`:

`TS2339: Property 'then' does not exist on type 'AsyncThunkAction<SomeType | undefined, void, {}>'.`

hook initiated properly:
```
export type AppDispatch = typeof store.dispatch;
export const useAppDispatch = () => useDispatch<AppDispatch>();
```
ps:
Previous working versions:
```
"@reduxjs/toolkit": "^1.6.1",
"react-scripts": "4.0.3",
```

**Comment by markerikson** [comment] 2021-12-20 21:04
Can you put together a project that actually shows this happening?

**Comment by phryneas** [comment] 2021-12-20 22:46
This is often caused by `react-redux` both in version `4.0.x` and `4.1.x` being present in `node_modules`. Can you make sure that is not the case? `npm ls react-redux` or `yarn why react-redux` might help you find the culprits.

**Comment by yibird** [comment] 2021-12-21 03:21
Hello, I encountered the same error as the creator. The react toolkit version is 1.7 1. The sample code is the same as the created code. I tried to use the NPM LS react Redux command. The react Redux version is 7.2 6. I don't know how to deal with this problem. Do you have a good solution? Thank you

**Comment by rgbutov** [comment] 2021-12-22 18:13
> 
<img width="320" alt="Screen Shot 2021-12-22 at 10 13 18 AM" src="https://user-images.githubusercontent.com/7040394/147137057-31d85ffd-7d18-4597-a129-7f0606d6d3f2.png">

**Comment by markerikson** [comment] 2021-12-22 18:22
Hmm.  Yeah, we'd really need to see a project that demonstrates the problem to get an idea of what's going on.

**Comment by rgbutov** [comment] 2021-12-22 18:46
> Hmm. Yeah, we'd really need to see a project that demonstrates the problem to get an idea of what's going on.

will add sample project soon :)

**Comment by rgbutov** [comment] 2021-12-22 19:01
> Hmm. Yeah, we'd really need to see a project that demonstrates the problem to get an idea of what's going on.

So can you pull it and try to run:
https://github.com/rgbutov/redux-toolkit-error
I have the same issue in my project

**Comment by phryneas** [comment] 2021-12-22 19:04
@rgbutov did you forget to push/commit? that looks like an unmodified CRA project.

**Comment by rgbutov** [comment] 2021-12-22 19:07
> @rgbutov did you forget to push/commit? that looks like an unmodified CRA project.

yes:) Sorry - already pushed commit:)

**Comment by rgbutov** [comment] 2022-01-07 04:47
any updates? :)

**Comment by rgbutov** [comment] 2022-01-20 04:16
....

**Comment by phryneas** [comment] 2022-01-20 07:07
Sorry, real life is very stressful right now. Looking at this, I'm pretty much as irritated as you are, this should be working.

The only idea I have here is that something in the redux types might have gone wrong - @markerikson  do you have any idea?

**Comment by lindapaiste** [comment] 2022-02-06 05:27
I can't explain exactly *why* you get this particular error, but you can fix it by using stricter types on your reducer.

This right here basically wipes out all known type information and says "anything can be anything":
```
const rootReducer = (state: any, action: any) => {
	return combinedReducer(state, action);
};
```

The `combinedReducer` already is your root reducer.  There's no need to wrap in another function.  Just do this:
```
export const rootReducer = combinedReducer;
```
and the error on `.then()` goes away.

**Comment by markerikson** [comment] 2022-02-20 16:57
Closing as this sounds like a setup issue.

**Closed by markerikson** 2022-02-20 16:57 UTC

**Comment by rgbutov** [comment] 2022-02-20 16:58
Setup issue??? Oo..... no comments...

**Comment by rgbutov** [comment] 2022-02-20 16:59
> I can't explain exactly *why* you get this particular error, but you can fix it by using stricter types on your reducer.
> 
> 
> 
> This right here basically wipes out all known type information and says "anything can be anything":
> 
> ```
> 
> const rootReducer = (state: any, action: any) => {
> 
> 	return combinedReducer(state, action);
> 
> };
> 
> ```
> 
> 
> 
> The `combinedReducer` already is your root reducer.  There's no need to wrap in another function.  Just do this:
> 
> ```
> 
> export const rootReducer = combinedReducer;
> 
> ```
> 
> and the error on `.then()` goes away.

Using **any** isn't a solution for typescript ....

**Comment by markerikson** [comment] 2022-02-20 17:01
@rgbutov the point is that your reducer setup was wrong to begin with, on multiple levels:

- that `combinedReducer` was unnecessary (at least in this example), and also typed wrong
- you could have done `reducer: {user: userReducer}` as an argument to `configureStore` itself
- and yes, you really should _not_ be using `any` anywhere in this code at all

**Comment by rgbutov** [comment] 2022-02-20 17:15
> @rgbutov the point is that your reducer setup was wrong to begin with, on multiple levels:
> 
> 
> 
> - that `combinedReducer` was unnecessary (at least in this example), and also typed wrong
> 
> - you could have done `reducer: {user: userReducer}` as an argument to `configureStore` itself
> 
> - and yes, you really should _not_ be using `any` anywhere in this code at all
> 
> 
> 
> It's possible none of that was related to the actual issue you initially reported, but if that's the case, this isn't a good reproduction that would help us understand what _is_ happening.

Again oO - this is just a sample, real application has a lot of reducers :)
This actual setup is from official  docs.
This sample is perfect representation of problem with new version of lib.

**Comment by markerikson** [comment] 2022-02-20 17:19
@rgbutov I think you're missing what I'm saying :(

Per comment from lindapaiste, **the example itself is broken because it uses `any` in the `rootReducer`**.

If that's what your _real_ code does, then the real code itself is broken.

If that's _not_ what the real code does, then the _example_ is broken.

**Comment by markerikson** [comment] 2022-02-20 17:37
And just as confirmation that the `rootReducer` is the issue - I cloned the repo and made the following change, and now `App.tsx` works correctly:

```ts
// reducers.ts
type RootReducer = typeof combinedReducer;

const rootReducer : RootReducer = (state, action) => {
	return combinedReducer(state, action);
};
```

result:

![image](https://user-images.githubusercontent.com/1128784/154856013-5a0c19dc-c31f-482d-a938-ca82b0be7991.png)

So yes, **don't use `any` while defining reducers**.

(and for that matter, please use the "builder callback` syntax inside of `createSlice` rather than the "object" syntax)
