### ISSUE TITLE
Unexpected upsert behavior of createEntityAdapter

### ISSUE THREAD

**Issue by aethelz** [reduxjs/redux-toolkit#721] opened 2020-09-09 19:18 UTC
Due to upsert using mutable update logic [under the hood](https://github.com/reduxjs/redux-toolkit/blob/2de2d0677ccd4a9a4a7fb205580a550b1ad70c98/src/entities/unsorted_state_adapter.ts#L162) upserting an object with optional fields leads to unexpected behavior, all props are updated as they should  be, but optional fields are not properly removed.

[Minimal reproducible example](https://stackblitz.com/edit/typescript-jaiwwk?file=index.ts)

I think this quirk either deserves a mention in the docs or, as a solution, we could just replace entire object on upsert if ID is already present (I can make a quick PR if it is a good idea).

**Comment by msutkowski** [comment] 2020-09-09 21:38
In general, when you use `upsert` with a database they don't automatically drop existing properties for you - they simply insert the new entry as-is or update the fields with a conflict. The behavior you're describing would typically run as a separate transaction, or the entry would be modified before calling `upsert`, and that's exactly what you should do here. If you have optional properties in a schema where you desire this behavior, you should just process the object before calling upsert and setting those optional fields to `undefined`. In your example, that'd look like:

```js
booksSlice.actions.bookUpdate({ id: "testID", title: "OtherBook", comment: undefined })
```

**Comment by markerikson** [comment] 2020-09-10 00:26
Silly question - does that actually correctly remove the fields you marked as `undefined`?

But yeah, "upsert" implies _additive/overwriting_ behavior from my perspective.  It's not going to _remove_ fields.

So, working as intended as far as I can see.

**Closed by markerikson** 2020-09-10 00:26 UTC

**Comment by msutkowski** [comment] 2020-09-10 00:49
Surprisingly, it does! https://stackblitz.com/edit/typescript-nq8cve?file=index.ts - I still don't know if I trust that, but its hard to say what the actual right approach is without a little more context :tada:
