### ISSUE TITLE
RTKQ: Get loading state of a single mutation in different components

### ISSUE THREAD

**Issue by EliseyMartynov** [reduxjs/redux-toolkit#1513] opened 2021-09-15 13:49 UTC
Hello! I've a following problem:

- Imagine we have some POST mutation hook to an endpoint in a X component that's inside Y component.
- **The problem**: I can get a loading state of the mutation in X - where it has been called - but I can't access this loading state in Y. That's feeling like a really disadvantage because it's a really regular case when you need to get a loading state of a single mutation in different components.
- I've already read that a mutation is unique and doesn't share data between different components. But there is no solution for that regular case? I know we can store some loading field in Redux and dispatch it in a mutation but... hey, I go for RTKQ because I don't want any loading fields in my Redux.

Thank you in advance! :)

**Comment by phryneas** [comment] 2021-09-15 15:55
This is currently being worked on in #1477 and will be possible in the next minor release.

**Comment by magistrfox** [comment] 2021-09-15 18:04
> This is currently being worked on in #1477 and will be possible in the next minor release.
@phryneas Thank you very much for a such quick replying me as always! :) Could you maybe please tell me if that's possible - how long it could take for the next release?

**Comment by phryneas** [comment] 2021-09-15 18:30
I *assume* somewhere around the 1-2 months mark, but I can't tell a 100%.

You can *try* #1477 already if you want to, but there will be some bugs or race conditions with it at this point I still have to fix.

Installation instructions are in [the CodeSandbox build page](https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/1477).

With that, you would use it like
```js
const [trigger, result] = useMyMutation({ fixedCacheKey: "myCacheKey" })
```

That cache key would be shared over components and *never cleaned up*, so the result would stay around until you call either `result.reset()` or trigger another mutation with the same cache key.

**Comment by magistrfox** [comment] 2021-09-16 07:42
> I _assume_ somewhere around the 1-2 months mark, but I can't tell 100%. A lot going on atm.
> 
> You can _try_ #1477 already if you want to, but there will be some bugs or race conditions with it at this point I still have to fix.
> 
> Installation instructions are in [the CodeSandbox build page](https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/1477).
> 
> With that, you would use it like
> 
> ```js
> const [trigger, result] = useMyMutation({ fixedCacheKey: "myCacheKey" })
> ```
> 
> That cache key would be shared over components and _never cleaned up_, so the result would stay around until you call either `result.reset()` or trigger another mutation with the same cache key.

Thank you! But seems like `https://pkg.csb.dev/reduxjs/redux-toolkit/commit/4b389bff/@rtk-query/graphql-request-base-query` has 404 error.

**Comment by magistrfox** [comment] 2021-09-16 15:22
@phryneas We caught strange behavior with your current PR when we use a mutation in another component we get `reset` field `undefined` and also `originalArgs` `undefined`. We really need `reset` field because it does the work for us.

[**The sandbox to test it**](https://codesandbox.io/s/gifted-knuth-cpncq?file=/src/AnotherComponent.js)

**Comment by phryneas** [comment] 2021-09-16 15:48
@magistrfox Whoa, good catch, thank you! 

Coincidentally there is a TODO in #1277 that will make it possible to *solve* this, but it might take some time untangling everything that is going on here.

**Comment by XiyuChen-95** [comment] 2021-09-16 18:27
Hi, I am facing a similar problem as well, I have tried the cached key but it is returning a typescript error. For my end, I am implementing a search form, within the search form component I am calling to fetch data from the backend, and in some other component, I need to display the data fetched from the search form component. Currently, I am not able to accomplish this using RTKQ, is there any way other than using the cached key that could accomplish this? I am thinking that perhaps I could try creating a slice to store the data and use it across the project?

**Comment by phryneas** [comment] 2021-09-17 06:12
@XiyuChen-95 have you also installed the experimental build of RTKQ as stated?

Generally: no, in the current RTKQ version there is nothing else you can do except move the hook call up to a common parent and passing everything to both components via props.

**Comment by XiyuChen-95** [comment] 2021-09-17 17:38
@phryneas yea, I installed the experimental build from the codesandbox build page, and it is giving me an error of below:
```Argument of type '{ fixedCacheKey: string; }' is not assignable to parameter of type 'UseMutationStateOptions<MutationDefinition<QueryParamType, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, never, RosbagType[], "rootApi">, ({ ...; } & { ...; }) | ... 2 more ... | ({ ...; } & ... 2 more ... & { ...; })>'.
  Object literal may only specify known properties, and 'fixedCacheKey' does not exist in type 'UseMutationStateOptions<MutationDefinition<QueryParamType, BaseQueryFn<string | FetchArgs, unknown, FetchBaseQueryError, {}, FetchBaseQueryMeta>, never, RosbagType[], "rootApi">, ({ ...; } & { ...; }) | ... 2 more ... | ({ ...; } & ... 2 more ... & { ...; })>'```

**Comment by XiyuChen-95** [comment] 2021-09-17 19:10
Seems like the solution for now (other than the experimental build) would be to combine RTKQ with Toolkit by creating a slice and store the fetched data into the state, and grab the piece of state by using the selector hook in another component.

**Comment by phryneas** [comment] 2021-09-17 21:15
@XiyuChen-95 that's super weird, if you try it in [this CodeSandbox](https://codesandbox.io/s/examples-query-react-basic-forked-nh8z7?file=/src/App.tsx) the typings do work. 
The only thing I can think about is that you maybe have multiple versions of the library installed - other than that I can't really help without a reproduction, sorry :(

**Comment by XiyuChen-95** [comment] 2021-09-17 22:20
@phryneas Actually, that you mentioned with the library installation, I went to check my dependencies and found that the build isn't installed correctly. Just to make sure if I did the installation process correctly I did the command below:
```yarn add https://pkg.csb.dev/reduxjs/redux-toolkit/commit/4b389bff/@reduxjs/toolkit https://pkg.csb.dev/reduxjs/redux-toolkit/commit/4b389bff/@rtk-query/graphql-request-base-query```

and the error for installation I've got is as below:

```error An unexpected error occurred: "https://pkg.csb.dev/reduxjs/redux-toolkit/commit/4b389bff/@rtk-query/graphql-request-base-query: Request failed \"404 Not Found\"".```

**Comment by markerikson** [comment] 2021-09-17 22:33
@XiyuChen-95 I don't think you need to be installing the `graphql-request-base-query` package, do you?

**Comment by XiyuChen-95** [comment] 2021-09-17 22:51
@markerikson I copied the yarn install command from the build instruction directly. I thought that the graphql package is needed. So an installation of the package is done. Weird thing is that I am still getting the typescript error as above. The dependency under my json file shows 
```
    "@reduxjs/toolkit": "https://pkg.csb.dev/reduxjs/redux-toolkit/commit/4b389bff/@reduxjs/toolkit",
    "@rtk-incubator/rtk-query": "^0.3.0",
```

**Comment by markerikson** [comment] 2021-09-18 02:39
@XiyuChen-95 The GraphQL package exists in the RTK repo, so it's probably being built as part of the CSB.  But, it doesn't sound like you're using it, so you shouldn't try to install it.

Also, the `@rtk-incubator/rtk-query` package is very obsolete - that's the early alpha version of RTK Query, before we moved the code into RTK itself. You should uninstall that.

**Comment by XiyuChen-95** [comment] 2021-09-18 18:11
@markerikson Thanks for the explanation and advise, I will uninstall the `@rtk-incubator/rtk-query` package and try to see if the `fixedCachedKey` property works, otherwise I will try using entity or slice to share the data in another component

**Comment by magistrfox** [comment] 2021-09-21 09:52
@XiyuChen-95 Hello! My colleague had the same issue. Try to clear your cache and node_modules and reinstall entire dependencies. It should help.

**Comment by markerikson** [comment] 2021-11-26 22:24
I'm pretty sure this was resolved by #1477 and is available as of https://github.com/reduxjs/redux-toolkit/releases/tag/v1.7.0-beta.0 .

**Closed by markerikson** 2021-11-26 22:24 UTC
Labels: rtk-query

**Comment by edgar-roc** [comment] 2022-06-21 16:20
Hello guys, do we have a fix for this, How I can get the isLoading value from a mutation in order component?

thanks in advance, I'm stuck there :)

**Comment by markerikson** [comment] 2022-06-21 16:22
@edgar-roc : yes, per the last comment, the answer is to pass in a fixed cache key for the mutation:

https://redux-toolkit.js.org/rtk-query/usage/mutations#shared-mutation-results
