### ISSUE TITLE
Setting createSlice.initialState as type "Element" creates memory leak

### ISSUE THREAD

**Issue by als9xd** [reduxjs/redux-toolkit#337] opened 2020-01-28 18:24 UTC
I have a minimal reproducible example here. I have tried on multiple machines (linux and windows) with up to 32gb ram and have also tried increase max-old-space-size but am still unable to build for prod or run in webpack dev server.

https://github.com/als9xd/memory-leak-example

Run `yarn` then either `yarn build` or` yarn start`

Here is the specific code that crashes:

```
import { createSlice } from '@reduxjs/toolkit'
import { createStore, combineReducers } from 'redux'

export const testSlice = createSlice({
  name: 'slice',
  initialState: null as Element | null, // "Element" type specifically crashes the app 
  reducers: {
    load: (state) => {
      return null;
    },
  },
});

const reducer = combineReducers({
  testSlice: testSlice.reducer,
});

export const store = createStore(reducer);
```

This is the error generated

```
Starting the development server...
Files successfully emitted, waiting for typecheck results...

<--- Last few GCs --->

[23992:0000015A993D3D50]    71314 ms: Scavenge 2025.9 (2082.4) -> 2025.1 (2082.9) MB, 9.3 / 0.0 ms  (average mu = 0.289, current mu = 0.260) allocation failure
[23992:0000015A993D3D50]    71323 ms: Scavenge 2025.9 (2082.9) -> 2025.1 (2083.4) MB, 6.9 / 0.0 ms  (average mu = 0.289, current mu = 0.260) allocation failure
[23992:0000015A993D3D50]    71336 ms: Scavenge 2026.1 (2083.4) -> 2025.2 (2084.4) MB, 8.6 / 0.0 ms  (average mu = 0.289, current mu = 0.260) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00000030D325C5C1]
Security context: 0x02136421e6e9 <JSObject>
    1: trySymbolTable(aka trySymbolTable) [00000316FB5867A9] [C:\Users\aschrimpf\Documents\github\memory-leak-example\node_modules\typescript\lib\typescript.js:~35981] [pc=00000030D3DC5CE8](this=0x037a685026f1 <undefined>,symbols=0x010ae4786561 <Map map = 0000009904D84359>,ignoreQualification=0x037a685026f1 <undefined>)
    2: getAccessibleSymbolChainFromSymb...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6C932C6AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF6C9307416 node::MakeCallback+4534
 3: 00007FF6C9307D90 node_module_register+2032
 4: 00007FF6C962189E v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF6C96217CF v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF6C9807F94 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF6C97FEF76 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF6C97FD5CC v8::internal::ScavengeJob::operator=+17980
 9: 00007FF6C9806317 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF6C9806396 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF6C9930637 v8::internal::Factory::NewFillerObject+55
12: 00007FF6C99AD826 v8::internal::operator<<+73494
13: 00000030D325C5C1
```

**Comment by phryneas** [comment] 2020-01-28 18:34
This is interesing. If I had to bet on it, I'd say that `Draft<Element | null>` creates this memory leak, which would not really be the fault of RTK or immer, but a bug in the TypeScript compiler.

I'll try to investigate this in the next few days, but if you want to do some eperimentation on your own:
* does this happen with `Draft<Element>` or `Draft<Element | null>` ?
* are you on the latest TypeScript version?
* maybe they already have an issue on this?

**Comment by markerikson** [comment] 2020-01-28 18:48
Yeah, this is pretty bizarre, but I also don't see it as actually being RTK-related at all.  The kind of stack trace you showed indicates this is some problem with the TypeScript compiler itself.

Looking at the code sample here and in the repo, I don't even know what `Element` is.  It's not being imported in that file, so I have no idea where it's coming from or what it's supposed to be.

Given all that, I'm going to close this as not being relevant here.  However, I'd be interested in hearing what the actual problem is once it's figured out on the TS side.

**Closed by markerikson** 2020-01-28 18:48 UTC

**Comment by als9xd** [comment] 2020-01-28 19:13
@phryneas 

1.  It also happens with Draft<Element | null>
2. I am on latest typescript (3.7.5)
3. Don't see any issues immediately

**Comment by phryneas** [comment] 2020-01-28 20:34
@als9xd funny thing: I can't reproduce it with your example. So sorry, you're on your own  :/
I suggest you open an issue over at https://github.com/microsoft/typescript

Just for reference: I'm running node v10.15.3 - that might be the difference between us. (OS: NixOS)
