### ISSUE TITLE
TS Bug found while testing the 2.0.0-beta.4

### ISSUE THREAD

**Issue by wirdehall** [reduxjs/redux-toolkit#3862] opened 2023-11-09 18:26 UTC
When creating a listener middleware that matches an action using `matcher: isAnyOf(...)` it's no longer getting the correct action type. In this instance it's missing that it's a payload action.

Here's a code example:

```
const notificationSlice = createSlice({
  name: 'notification',
  initialState,
  reducers: {
    addNotification: {
      reducer: (state, { payload: { notificationType, notification, autoDismissInMs, id } }: PayloadAction<FullNotificationActionPayload>) => {
        state[notificationType].push({ notification, autoDismissInMs, id });
      },
      prepare: (payload: NotificationActionPayload) => ({ payload: { ...payload, id: nanoid() } })
    },
  }
})

export const { addNotification } = notificationSlice.actions;
```

And where I create my listenerMiddleware:

```

notificationEffects.startListening({
  matcher: isAnyOf(addNotification),
  effect: async (action, listenerApi) => {
    const { autoDismissInMs, notificationType, id } = action.payload;
    .
    .
    .
```

Here it will complain that action.payload does not exist since action is typed as Action instead of PayloadAction.

This is not a big issue in this example since I shoud probably just use `actionCreateor`as a matcher instead, then action get's the correct type.

But the same listener middleware has another listner where I match multiple actions like this:
```
notificationEffects.startListening({
  matcher: isAnyOf(addSuccess, addNotice, addError),
  effect: async (action, listenerApi) => {
    listenerApi.dispatch(addNotification(action.payload));
  },
});
```
The same problem here.
This worked prior to upgrading to the beta.

**Comment by markerikson** [comment] 2023-11-09 18:54
Huh, that's surprising.  We really didn't change anything about the listener middleware, other than going from `AnyAction` to `UnknownAction` in some places.

Could you put together a project that reproduces this?  Also, what version of TS are you on?  And is there only one version of the `redux` core installed, or multiple versions?

**Comment by EskiMojo14** [comment] 2023-11-09 19:15
i'm not sure what changed the inference behaviour, but it's worth noting that moving the matcher definition outside of the startListening call will work:
```ts
const isNotificationAction = isAnyOf(addSuccess, addNotice, addError)
notificationEffects.startListening({
  matcher: isNotificationAction ,
  effect: async (action, listenerApi) => {
    listenerApi.dispatch(addNotification(action.payload));
  },
});
```

**Comment by wirdehall** [comment] 2023-11-09 20:13
@markerikson : Here's a minimal project that shows this error: https://github.com/wirdehall/bug-redux-toolkit-beta
It doesn't have enough files to run but we don't need to as we just need to see the TS error.
Typescript version: 5.0.2.
It's the only version of redux installed.

@EskiMojo14: Interesting that it changes behaviour when we move it out. I tried it and in my case it still does not work since notification types are not set to string but to "error" | "notice" | "success".

Hum, yeah that seams like a good way of going about it. Might change that up in my code.

Still, I didn't report this specificlly for my use-case as I can easily solve this by just type-casting.
I thought it might be a good idea to report as this did work in 1.9 but not in the 2.0 beta and it might affect alot of people.
And most importanly, it was nice when it just worked 😁

**Comment by EskiMojo14** [comment] 2023-11-23 23:22
After some more investigation, it appears this was already an issue for TS in 1.9?
![image](https://github.com/reduxjs/redux-toolkit/assets/18308300/937a7242-665f-4175-a743-bf092ad7c541)

The difference being that AnyAction (the type in 1.9) will just return `any` when you access unknown fields, whereas the new type (Action) will not let you access unknown fields. This is why you got new type errors - but if you checked in 1.9, I suspect that they would have just been `any` and all type safety had gone out the window.

If anything, out of the two I'd argue the new behaviour is *safer* - though obviously neither is ideal, and you can define the matcher outside of the startListening call to get the proper narrowing behaviour as discussed.

**Closed by EskiMojo14** 2023-11-23 23:22 UTC

**Comment by EskiMojo14** [comment] 2024-09-24 11:13
for future reference, this seems to be another issue fixed by @Andarist's PR here: https://github.com/microsoft/TypeScript/pull/54183

playground using the build from the PR, proving it fixes the issue: https://tsplay.dev/wE6RVN
