### ISSUE TITLE
Return type of transformResponse on enhanceEndpoints can not differ from original definition in createApi

### ISSUE THREAD

**Issue by bkempe** [reduxjs/redux-toolkit#1441] opened 2021-08-25 15:05 UTC
Currently, the return type of `transformResponse` on `enhanceEndpoints` has to match the original return type from `createApi`.
This diminishes the value and ability of `enhanceEndpoints`:
Often, it is preferred to have client code use different shapes than the ones exposed by an API and `transformResponse` is the mechanism to do so.
However, once RTK codegen is used, `transformResponse` should be defined on `enhanceEndpoints` and not on the (generated) `createApi`.

#### Example
Using the `enhancedEndpoints` example [from the docs](https://redux-toolkit.js.org/rtk-query/usage/code-generation), this usage of `transformResponse` currently fails to compile:
```ts
getPetById: {
    providesTags: (result, error, arg) => [{type: 'Pet', id: arg.petId}],
    transformResponse: ({id, name, category, photoUrls, tags, status}) => ({id, name}),
},
```

**Comment by quodlibetor** [comment] 2022-04-08 20:46
(Thanks for rtkq, I'm transitioning some code to it now and it's amazing.)

I don't know if one of the things that's holding this up is lack of ideas for how to make it ergonomic, but in case that is the issue I have an idea that might work as a jumping off point for brainstorming.

In the OpenAPI context -- which is where I think of this coming up the most -- would it be possible to handle this by treating the enhancing api as an intermediate phase specified in config, changing the way that code generation ends up?

What I'm imagining is that where right now the `outputFile` contains the result of `injectEndpoints` its types, _and_ all the hook exports, you could just generate another file that has all the modified types and use statements.

I can imagine that if a user specifies a trio of new `enhance*` fields it might be possible to make make this work pretty well.

As a walkthrough of the simple case of only one input file:

Where right now you specify:

```typescript
const config = {
    schemaFile: "...",
    apiFile: "empty.ts",
    apiImport: "empty",
    outputFile: "api.ts",
}
```

You could add `enhanceInputFile`, `enhanceFile`, `enhanceImport`:

```typescript
const config = {
    schemaFile: "...",
    apiFile: "empty.ts",
    apiImport: "empty",
    enhanceInputFile: "middle.ts", // <-- new
    enhanceInputExport: "middle",  // <-- new
    enhanceFile: "enhance.ts",     // <-- new
    enhanceImport: "enhance",      // <-- new
    outputFile: "api.ts"
}
```

The openapi-codegen program then generates the `enhanceInputFile` looks exactly like the current `outputFile` *except* it does not include any of the `use*` reexports. This is mostly just to make it more clear that it should not be used by itself.

After that, the `enhanceFile` contains either an `middle.enhanceEndpoints` or some new api that returns a new object. This file is written by humans who would like to provide transforms/etc.

Then, the openapi codegen reads this new file, does magic with types -- or just requires that all types be defined explicitly in the middle file -- and outputs basically a duplicate of the `inhanceInputFile` but with fully correct types.

Does that seem... possible?

**Comment by Hypnosphi** [comment] 2022-06-30 20:13
> It is theoretically possible, but depending on what file you import from you will get things of different types - and enhanceEndpoints does not create a new instance, but changes the original instance, but cannot change it's types, so you'd have multiple versions of the same api with the same (enhanced) behaviour, but very different types.

That's no problem for me personally, as I'm only going to import from the `enhancedApi` file (and maybe even enforce it with eslint or something)

**Comment by phryneas** [comment] 2022-06-30 22:38
If you want to open a PR to it, I'd be open for it. I just don't have the time to work on that at the moment.

**Comment by misterjame** [comment] 2022-10-12 09:30
+1

I am using codegen for GraphQL queries and would like transform the result.

**Closed** 2023-04-16 21:15 UTC
Labels: enhancement, rtk-query
