### ISSUE TITLE
Enhancement: Support onError,    onSettled,    onSuccess for Query Hook options

### ISSUE THREAD

**Issue by suupham2506** [reduxjs/redux-toolkit#1434] opened 2021-08-22 14:50 UTC
Currently, I can not handle actions on query success or error. I need some ways to handle it.
Hopefully, these requests should be applied for the next version.
Any suggestions?

**Comment by markerikson** [comment] 2021-08-22 15:53
Duplicate of #1383 .

**Closed by markerikson** 2021-08-22 15:53 UTC
