### ISSUE TITLE
Use `serialize-error` module (`Error#cause` support)

### ISSUE THREAD

**Issue by fregante** [reduxjs/redux-toolkit#2392] opened 2022-06-08 08:34 UTC
I noticed that RTK’s error serialization is rather simple:

https://github.com/reduxjs/redux-toolkit/blob/64a30d83384d77bcbc59231fa32aa2f1acd67020/packages/toolkit/src/createAsyncThunk.ts#L94-L107

For example this does not support nested errors, like the new `cause` property: https://v8.dev/features/error-cause

I know RTK supports specifying a custom `serializeError` as an option, but it'd be great to support the `cause` property out of the box, perhaps using an existing solution for error serialization:

- https://github.com/sindresorhus/serialize-error

**Comment by phryneas** [comment] 2022-06-08 10:17
Honestly, this is working *exactly* as intended here. 

`createAsyncThunk` knows two different kinds of errors:
* known errors - this would be this kind of error: you know that they will happen, you know they can have a specific structure. You should handle those in your code and use `rejectWithValue`.
* unknown errors - this could be an access to `undefined.something`, an out-of-bounds array access, a bundler error that only surfaces at runtime or a string that is being thrown somewhere in a library you are consuming and that you don't expect. We don't know anything about those errors. So the code you are pointing to tries to get them into a "predictable shape" so they can be at least handled at some way in the end.

So in the end: you should probably handle those errors and use `rejectWithValue`, or your well-known errors will get mixed up with unpredictable stuff.

**Comment by markerikson** [comment] 2022-06-08 14:02
It'd be easy enough to add another field to the known list, but yeah, I don't want to add another dep here.

**Comment by markerikson** [comment] 2022-07-01 01:23
Going to close this for now - I don't think this is urgent enough for us to change.

**Closed by markerikson** 2022-07-01 01:23 UTC

**Comment by kasparkallas** [comment] 2022-07-12 06:27
I'd also like to see `Error.cause` serialized because it's a good convention which is now supported both in Node and browsers.

**Comment by kasparkallas** [comment] 2022-07-18 08:59
1. Add error's `cause` field to the known list and recursively serialize the errors (i.e. chain the errors)
2. Make it possible to override `serializeError` for RTK-Query

Interested in both?

For 1, here are some references:
* `error.cause` browser support (part of ES2022): https://caniuse.com/mdn-javascript_builtins_error_cause
* `error.cause` added to Node 16.9: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V16.md#16.9.0
* `error.cause` added to Node documentation: https://github.com/nodejs/node/pull/43830
* `error.cause` added to TypeScript: https://github.com/microsoft/TypeScript/issues/45167

**Comment by kasparkallas** [comment] 2022-07-22 10:40
Ping! @phryneas @markerikson

**Comment by phryneas** [comment] 2022-07-22 10:44
Honestly, at this point only interested in B - A would probably make the types explode.
