### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'merge')

### ISSUE THREAD

**Issue by karanshah229** [reduxjs/redux-toolkit#3567] opened 2023-06-29 10:46 UTC
Getting this error on Next.js project:

<img width="952" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/42066323/6bc958c3-67d3-42e1-ad83-bf8ac678825e">

Code for the `rtkQueryErrorLogger`:
```js
import { isRejectedWithValue } from '@reduxjs/toolkit';

import { logger } from 'src/utils/logger';

import type { Middleware, MiddlewareAPI } from '@reduxjs/toolkit';

export const rtkQueryErrorLogger: Middleware = (_api: MiddlewareAPI) => (next) => (action) => {
  if (isRejectedWithValue(action)) {
    logger.error({
      message: `Error in API call ${action?.meta?.baseQueryMeta?.request?.url}`,
      error: action,
    });
  }

  return next(action);
};
```

Stuck on this for a while, any help is appreciated.

cc: @phryneas

**Comment by EskiMojo14** [comment] 2023-06-29 10:54
if you remove the rtkQueryErrorLogger middleware from your store, does the error still occur?

i don't see anything immediately wrong with the middleware itself.

**Comment by karanshah229** [comment] 2023-06-29 10:55
The trouble is that it's an intermittent issue.
So I can't reproduce it every time and hence can't tell if it solved the issue or not.

I can post some snippets if you need of the store, rootAPI or anything else.
Can 't give the repo since it's a work repo

**Comment by karanshah229** [comment] 2023-06-29 11:03
I think this is causing the issue:

```js
extractRehydrationInfo(action, { reducerPath }) {
  if (action.type === HYDRATE) {
    return action.payload[reducerPath];
  }
  return undefined;
},
```

The reason I had done this is that ESLint throws an error otherwise:
```js
Expected to return a value at the end of method 'extractRehydrationInfo'
```

What should be the default return instead ?

**Comment by EskiMojo14** [comment] 2023-06-29 11:13
returning undefined is fine, since it's the same as not returning as far as the caller is concerned.

the only place in the codebase i can find `merge` being accessed is below:

https://github.com/reduxjs/redux-toolkit/blob/24fc34392d249573fd14088db8daea10e848de41/packages/toolkit/src/query/core/buildSlice.ts#L178-L180

This would suggest you're somehow getting a query thunk fulfilled for an endpointName that isn't actually in the endpoint definitions, which is very odd.

Would you be able to post your endpoint definitions?

If it's intermittent, it could be related to something in your build process, such as hot module reloading.

**Comment by karanshah229** [comment] 2023-06-29 11:21
Store.ts

```ts
import { configureStore } from '@reduxjs/toolkit';
import { setupListeners } from '@reduxjs/toolkit/query';
import { Context, createWrapper } from 'next-redux-wrapper';

import { rtkQueryErrorLogger } from './middlewares/rtkQueryErrorLogger';
import { rootApi } from './services/common/rootApi';
import { isDev } from './utils/common';

export const makeStore = (ctx?: Context) =>
  configureStore({
    reducer: {
      [rootApi.reducerPath]: rootApi.reducer,
    },
    middleware: (getDefaultMiddleware) =>
      getDefaultMiddleware({
        thunk: {
          extraArgument: ctx,
        },
        serializableCheck: false,
      })
        .concat(rootApi.middleware)
        .concat(rtkQueryErrorLogger),
    devTools: isDev,
  });

const store = makeStore();
setupListeners(store.dispatch);

export type AppStore = ReturnType<typeof makeStore>;
export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = AppStore['dispatch'];

export default store;

export const wrapper = createWrapper<AppStore>(makeStore, {
  debug: isDev,
});
```

---

rootApi.ts
```ts
import { createApi, retry } from '@reduxjs/toolkit/query/react';
import { HYDRATE } from 'next-redux-wrapper';

import { isServer } from 'src/utils/common';

import { clientBaseQueryWithReAuth } from './clientFetchBaseQueryWithReAuth';
import { serverBaseQueryWithReAuth } from './serverFetchBaseQueryWithReAuth';

// initialize an empty api service that we'll inject endpoints into dynamically
export const rootApi = createApi({
  reducerPath: 'rootApi',
  baseQuery: retry(isServer ? serverBaseQueryWithReAuth : clientBaseQueryWithReAuth, {
    maxRetries: 0,
  }),
  keepUnusedDataFor: 60, // 1 minute
  /* istanbul ignore next */
  extractRehydrationInfo(action, { reducerPath }) {
    if (action.type === HYDRATE) {
      return action.payload[reducerPath];
    }
  },
  endpoints: () => ({}),
});
```

I won't be able to give the endpoint definition, but can give you the structure:
We have one `rootApi.ts` file and we load all our endpoint definitions in that using `injectEndpoints`

**Comment by EskiMojo14** [comment] 2023-06-29 11:26
everything you've posted seems fine, so i can only assume that the issue lies with one of your endpoint definitions. make sure you're not doing something strange like conditionally defining an endpoint definition. other than that, it's hard to advise further without code or a reproduction (or a [Replay](https://www.replay.io/))

**Comment by karanshah229** [comment] 2023-06-29 11:33
If you can just list possible causes, I can test for them on my end.

**Comment by Sigkar** [comment] 2023-08-02 19:03
I am currently experiencing this same error, causing me quite a bit of grief.

> I won't be able to give the endpoint definition, but can give you the structure:
We have one rootApi.ts file and we load all our endpoint definitions in that using injectEndpoints

I was set up like this, however I had to make some changes to our injections due to some of our op names between configuration files being duplicated. 

Our endpoints with the same op names would use the most recently injected op names endpoint/types for obvious reasons.

https://redux-toolkit.js.org/rtk-query/usage/code-splitting basically summed up the reason for splitting our APIs

> Calling injectEndpoints will inject the endpoints into the original API, but also give you that same API with correct types for these endpoints back. (Unfortunately, it cannot modify the types for the original definition.)

We're a bit behind on versions as well.
```
"@reduxjs/toolkit": "^1.8.0",
"@rtk-query/codegen-openapi": "1.0.0",
```

**Comment by karanshah229** [comment] 2023-08-03 05:27
@Sigkar 

> I was set up like this, however I had to make some changes to our injections due to some of our op names between configuration files being duplicated.

1. We don't have duplicate endpoint names.
2. What changes did you make ?
3. What is `op names` ?

**Comment by Sigkar** [comment] 2023-08-03 19:29
@karanshah229

2. I ended up fixing this by double checking my middlewares/reducers. I had a few missing
3. Op Names are just endpoint names in AWS API Gateway - sorry

**Comment by markerikson** [comment] 2023-08-16 15:32
Closing due to lack of reproduction.

**Closed by markerikson** 2023-08-16 15:32 UTC
