### ISSUE TITLE
redux toolkit query isLoading problem

### ISSUE THREAD

**Issue by phoique** [reduxjs/redux-toolkit#2255] opened 2022-04-18 11:50 UTC
Hello,

I have a problem or bug. I have an endpoint, I send a request, this endpoint is a get and its equivalent in rtk is queries. IsLoading returns true when there is no value in the cache, and status is pending. Status is being fulfilled isLoading is false. No problem until here. I am requesting again with a different body on the same endpoint, for example, if the endpoint is an endpoint where I pull users page by page, the status is pending again, but isLoading is false. The status is fulfilled isLoading is still false. In this case, I will look at the status to catch the loading status. What is isLoading for here?

- react: 17.0.2
- react-redux: 7.2.6
- @reduxjs/toolkit: 1.8.1

**Comment by phryneas** [comment] 2022-04-18 14:13
`isLoading` is only true for the first time a component is loading data
`isFetching` is true every time your component is loading data

**Comment by phoique** [comment] 2022-04-18 15:45
Yes, as you said, when I look now, isFetching is the value I will use. This time, in the status pending state, isSuccess is false in the first console log message. If the pending console log message is true, it becomes true before the request ends.

**Comment by phryneas** [comment] 2022-04-18 16:58
I am not sure what you are trying to explain here, I'm sorry.

**Comment by phoique** [comment] 2022-04-19 06:50
I understand you well. The problem is that when it is loaded for the first time, there is no problem, but when the body part of the same endpoint changes, isSuccess gives a strange result.

Result of a request made with the same endpoint in body modified after the first load: 
```
{
    "status": "pending",
    "isUninitialized": false,
    "isLoading": false,
    "isSuccess": false,
    "isError": false,
    "data": [],
    "isFetching": true
}
```
A console log output during the request pending phase:
```
{
    "status": "pending",
    "endpointName": "testEndpoint",
    "requestId": "j5Azky3K9F3vPtjSM1sHh",
    "originalArgs": {},
    "startedTimeStamp": 1650350214320,
    "isUninitialized": false,
    "isLoading": false,
    "isSuccess": true,
    "isError": false,
    "data": [],
    "isFetching": true
}
```
Output when status is fulfilled.
```
{
    "status": "fulfilled",
    "endpointName": "testEndpoint",
    "requestId": "j5Azky3K9F3vPtjSM1sHh",
    "originalArgs": {},
    "startedTimeStamp": 1650350214320,
    "data": [],
    "fulfilledTimeStamp": 1650350214848,
    "isUninitialized": false,
    "isLoading": false,
    "isSuccess": true,
    "isError": false,
    "currentData": [],
    "isFetching": false
}
```

Is isSuccess supposed to work like this? Shouldn't it be true after the request has finished?

**Comment by markerikson** [comment] 2022-06-29 02:21
I think we'd need to see a reproduction that shows this behavior to investigate further.

I'm going to close this as "working as intended" for now - if you can provide a repro, please comment and we can take another look.

**Closed by markerikson** 2022-06-29 02:21 UTC

**Comment by ra-hul-rv** [comment] 2023-07-12 05:30
having the same issue 
const { data, error, isLoading, refetch } = useGetPaymentsQuery(params, {
        refetchOnMountOrArgChange: true,
    });
isLoading value only changes initially when i change the params the call happens but the the is loading is still false 

also found an issue that i cant call refetch with new params the call always get initiated with the initial params

**Comment by phryneas** [comment] 2023-07-12 05:45
> isLoading value only changes initially when i change the params the call happens but the the is loading is still false

That is normal, `isLoading` is only `true` for the first fetch in the lifetime of a component, if no data was there before. After that, it's always `isFetching`

> also found an issue that i cant call refetch with new params the call always get initiated with the initial params

How do you do that? There is no "refetching with new params", it will just refetch.

**Comment by abaum-augu** [comment] 2023-11-02 08:53
> That is normal, isLoading is only true for the first fetch in the lifetime of a component, if no data was there before. After that, it's always isFetching

This is kind of weird and a bit not trivial IMO. Shouldn't isLoading be true again if it's the first time we fetch a query with different args (new query entry)?

**Comment by EskiMojo14** [comment] 2023-11-02 10:21
The point is that `isLoading` is only true if there is *no* data to display. This means you can use it to display a skeleton UI, for example. It would be bad UX to use a skeleton every time the component fetches something.

On the other hand, `isFetching` is true when the component is fetching anything, regardless of whether you already have data you can display. This means you can use it for less intrusive loading indicators, like a spinner, while still displaying the previous data.

```ts
const { isLoading, isFetching, data } = useGetDataQuery();

if (isLoading) {
  return <SkeletonTable />;
}

return (
  <>
    {isFetching && <Spinner />}
    <DataTable data={data} />
  </>
);

```

**Comment by adityasshinde** [comment] 2024-03-13 17:12
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const funnelApi = createApi({
  reducerPath: "funnelApi",
  baseQuery: fetchBaseQuery({
    baseUrl: process.env.REACT_APP_BASE_URL}),
  endpoints: (builder) => ({
    getFunnel: builder.query({
      query: () => "/funnel", 
    }),
    enterFunnel: builder.mutation({
      query: (id) => ({
        url: `funnel/${id}`,
        method: "POST",
      }),
    }),
  })
});

export const {
  useEnterFunnelMutation,
  useGetFunnelQuery,
} = funnelApi;

when I am calling useGetFunnelQuery in a page i.e.
  const {data,isLoading,isError}=useGetFunnelQuery();
the values of data, isLoading, isError are not changing at all, I am able to see the response data in network tab but the isLoading is still true.
I have also kept an useEffect to monitor values of them

  useEffect(() => {
  console.log(data,isLoading,isSuccess,isError);
  }, [data,isLoading,isError])
  
  why the values are not reflecting here
