### ISSUE TITLE
Error with tsc when attempting to import types from RTK Query using @reduxjs/toolkit 2.0.1

### ISSUE THREAD

**Issue by ryerrappa** [reduxjs/redux-toolkit#3970] opened 2023-12-10 14:53 UTC
>Sample repo reproducing the issue can be found here: https://github.com/ryerrappa/rtk-query-type-import-issue

- @reduxjs/tookit 2.0.1
- Vite 5.0.0
- Typescript 5.2.2
- tsconfig moduleResolution "bundler"

Receive the following error when attempting to import the `MutationTrigger` type.

```
Cannot find module @reduxjs/toolkit/dist/query/react/buildHooks
```

Using vite with the following tsconfig.

```json
{
  "compilerOptions": {
    "composite": true,
    "skipLibCheck": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}
```

**Comment by markerikson** [comment] 2023-12-10 14:57
Yeah, the problem is you're specifically referencing that path, and it doesn't exist :)

```ts
import {MutationTrigger} from "@reduxjs/toolkit/dist/query/react/buildHooks";
```

That type is actually internal - I don't think we export it.

Why are you trying to use it?

**Comment by ryerrappa** [comment] 2023-12-10 17:56
Ahh, thanks for letting me know. I was previously importing it on a pre 2.0 version of RTK. 

My use case was to send the mutation trigger along with some other args to a util function that performs some common functionality to all mutations belonging to a specific API. Something like


```typescript
export const handleSubmitFormMutation = async <
  ServiceMethod extends MutationTrigger<never>,
  RequestBody
>(
  serviceMethod: ServiceMethod,
  serviceMethodArg: Parameters<ServiceMethod>[0],
  successHandler: () => void,
  setFormError: UseFormSetError<RequestBody>
) => {
  try {
    await serviceMethod(serviceMethodArg).unwrap();
    // Some other stuff
  } catch (error) {
    // setting errors on the form
}

```

**Comment by lcharlois-neotys** [comment] 2023-12-11 08:09
Hello, 

I'm facing the same kind of issue with the UseQuery type.
```typescript
import { UseQuery } from '@reduxjs/toolkit/dist/query/react/buildHooks';
```

The use case is globally the same, having a utility method doing generic things on hooks results.

It will be nice to see these types being exported if possible.

**Comment by lcharlois-neotys** [comment] 2023-12-12 07:58
@markerikson Would you accept a PR for this issue?

**Comment by EskiMojo14** [comment] 2023-12-12 09:45
for what it's worth, with passing triggers I tend to just type them based on how I intend to use them. For example, with the above example:
```ts
export const handleSubmitFormMutation = async <
  MutationArg,
  RequestBody
>(
  serviceMethod: (arg: MutationArg) => { unwrap(): Promise<void> },
  serviceMethodArg: MutationArg,
  successHandler: () => void,
  setFormError: UseFormSetError<RequestBody>
) => {
  try {
    await serviceMethod(serviceMethodArg).unwrap();
    // Some other stuff
  } catch (error) {
    // setting errors on the form
  }
}
```
that way, you're having a minimum contract you expect from the trigger, and Typescript can compare your trigger against the contract to make sure it's compatible.

**Comment by TNMCook** [comment] 2023-12-15 20:50
I'm in the same boat as @lcharlois-neotys. I have a function that expects a query hook as a parameter and acts as a utility to handle various status changes and extract some common data. It looks something like this:

```
const usefulUtility = <ResultType>((queryHook: UseQuery<QueryDefinition<unknown, BaseQueryFn, string, ResultType>>, queryArg?: unknown) => {
    ...
    const {data, isSuccess, isError} = queryHook(queryArg);
    ...
    // Do useful stuff that would otherwise be repeated in multiple places 
    ...
}
```

It would be nice to have a type to easily encapsulate what a useWhateverQuery hook looks like. I've worked around it with my own type of `(arg?: QueryArg) => TypedUseQueryHookResult<ResultType, QueryArg, BaseQueryFn>`, but it would be nice to have a user accessible type for what a useSomethingQuery() looks like.

**Comment by ryerrappa** [comment] 2023-12-16 08:51
@EskiMojo14 That seems to work well. Thanks for your suggestion!

**Comment by lcharlois-neotys** [comment] 2024-02-02 09:44
@tylerlaprade I'm working on a PR to expose more types.

For `EndpointBuilder` and `EndpointDefinitions` you can already import them like this as they are exported.

```typescript
import { EndpointBuilder } from '@reduxjs/toolkit/query';
```

**Comment by tylerlaprade** [comment] 2024-02-02 17:31
<img width="969" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/5475199/83fa50e1-812c-4136-9bbd-79b84e0206af">
I was able to switch `EndpointDefinitions` but not `EndpointBuilder`. However, I'm still on version `1.9.7`, so that might explain why it isn't available.
<img width="402" alt="image" src="https://github.com/reduxjs/redux-toolkit/assets/5475199/37edef38-aa8b-4253-ab10-bb576dba6d67">

**Comment by kThayer2** [comment] 2024-02-02 20:00
Could we add UseLazyQuery as an exported type?

**Comment by EskiMojo14** [comment] 2024-02-02 20:01
@tylerlaprade correct, EndpointBuilder was first exported from 2.0.

@kThayer2 could you give an example of how you'd use it?

**Comment by kThayer2** [comment] 2024-02-02 20:06
@EskiMojo14 Good question!  We are mocking it for unit testing:
/**
 * @example
 * const [trigger, result] = mockLazyQuery(useLazyGetEquipmentListQuery, {
 *   result: {
 *     data: {
 *       the: 'data',
 *     }
 *   }
 * })
 * expect(result.data).toEqual({the: 'data'})
 */
export function mockLazyQuery<T extends MockUseLazyQuery>(
  useLazyQuery: UseLazyQuery<any>,
  options?: MockUseLazyQueryResult<T>,
) {
  throwIfNotMock(useLazyQuery)

  const trigger = options?.trigger ?? vi.fn()
  const result = {
    ...options?.result,
  }

  vi.mocked(useLazyQuery).mockImplementation(() => [trigger, result] as any)

  return {
    trigger,
    result,
  }
}

**Comment by EskiMojo14** [comment] 2024-02-12 22:25
The type helpers from https://github.com/reduxjs/redux-toolkit/pull/4147 have been released in [version 2.2.0.](https://github.com/reduxjs/redux-toolkit/releases/tag/v2.2.0)

For what it's worth @kThayer2 we generally recommend using the real hooks and real network requests, and intercepting using [MSW](https://mswjs.io/), rather than mocking hooks.

**Closed by EskiMojo14** 2024-02-12 22:25 UTC
Labels: bug, rtk-query, typescript

**Comment by tylerlaprade** [comment] 2024-02-13 21:05
Thanks @EskiMojo14! Would it be possible to add a type for `UseMutation` as well? That's my only remaining `dist/` import.

**Comment by EskiMojo14** [comment] 2024-02-13 21:33
@tylerlaprade `TypedUseMutation` is exported, it just takes different (friendlier) generics.

**Comment by shrouxm** [comment] 2024-03-21 17:34
I created a PR exposing one more type: https://github.com/reduxjs/redux-toolkit/pull/4289, merging would allow me to upgrade to RTK 2! :)

**Comment by gimi-anders** [comment] 2024-04-17 14:28
Can we also have `BaseQueryFn` exported?
