### ISSUE TITLE
File extension doesn't get updated in docs

### ISSUE THREAD

**Issue by pawan-poudel-github** [reduxjs/redux-toolkit#3200] opened 2023-02-23 15:33 UTC
![image](https://user-images.githubusercontent.com/113958713/220953958-cefec421-a369-48a0-9c8e-848aa06f8749.png)
Even I change the given code to javascript the file extension remain same in the redux toolkit docs.
see at [https://redux-toolkit.js.org/tutorials/rtk-query](https://redux-toolkit.js.org/tutorials/rtk-query)

**Comment by markerikson** [comment] 2023-02-23 16:42
Yep, that's a known limitation our current setup.  Also, this is a duplicate of #3044 .

**Closed by markerikson** 2023-02-23 16:42 UTC
